= Лицензия

Для работы с модулем «Docsvision 5. Платформа» требуется лицензия на систему «Docsvision 5.5».

Возможность использования специальных функций Docsvision определяется наличием в лицензии Docsvision дополнительных опций:

* «Docsvision СУБД PostgreSQL» – разрешает работу с БД PostgreSQL;
* «Docsvision Personal (VIP) Licenses» – разрешает использование неконкурентных лицензий, назначаемых отдельным пользователям (дополнительная информация в пункте xref:AssignmentofVipLicense.adoc[Назначение персональной лицензии]);
* {blank}
+
«Docsvision Внешние файловые хранилища» – разрешает использовать для хранения бинарных данных файлов внешние хранилища (подробности в разделе xref:External_Data_Storage.adoc[Настройка внешних хранилищ Docsvision]). Также в лицензии должны быть дополнительные опции, определяющие разрешенные типы хранилищ:

** «Docsvision Внешнее хранилище ФС» – разрешает использовать хранилище в файловой системе;
** «Docsvision Внешнее хранилище MSSQL» – разрешает использовать хранилище во внешней БД Microsoft SQL;
** «Docsvision Внешнее хранилище FileStream» – разрешает использовать хранилище FileStream внешней БД Microsoft SQL;
+
Если дополнительная опция «Docsvision Внешние файловые хранилища» отсутствует, для хранения бинарных можно будет использовать только БД Docsvision или FileStream базы данных Docsvision.
* «Docsvision Кластер AlwaysOn» – разрешает серверу Docsvision работать с кластером баз данных SQL Server AlwaysOn (подробности в разделе xref:AlwaysOn.adoc[Размещение БД Docsvision в группе доступности Microsoft SQL Server AlwaysOn]);
* «Docsvision кэш-сервер» – разрешает использовать внешний кэш-сервер для хранения данных серверного кэша Docsvision. Также в лицензии должна быть дополнительная опция, определяющая разрешенный тип кэш-сервера:
** «Docsvision кеш-сервер Redis» – разрешает использовать кэш-сервер Redis;
* «Docsvision Внешний полнотекстовый поиск» – разрешает использовать внешнюю систему полнотекстового поиска. Также в лицензии должна быть дополнительная опция, определяющая разрешенный тип системы полнотекстового поиска:
** «Docsvision Внешний полнотекстовый поиск ElasticSearch» – разрешает использовать внешнюю систему полнотекстового поиска ElasticSearch;
+
Если дополнительная опция «Docsvision Внешний полнотекстовый поиск» отсутствует, для полнотекстового поиска можно будет использовать только интегрированный в SQL Server полнотекстовый поиск.
* «Docsvision Архивная база данных» – разрешает серверу Docsvision вытеснять архивные карточки в отдельную (сателлитную) базу данных.
+
Если дополнительная опция «Docsvision Архивная база данных» отсутствует, данные архивных карточек будут храниться в основной БД Docsvision.

*На уровень выше:* xref:../topics/Required_resources.adoc[Необходимые ресурсы]
