= Лицензия

Для работы с модулем "{dv} 5. {pl}" требуется лицензия на систему "{dv} 5.5".

Возможность использования специальных функций {dv} определяется наличием в лицензии {dv} дополнительных опций:

* "{dv} СУБД PostgreSQL" – разрешает работу с БД PostgreSQL;
* "{dv} Personal (VIP) Licenses" – разрешает использование неконкурентных лицензий, назначаемых отдельным пользователям (дополнительная информация в пункте xref:AssignmentofVipLicense.adoc[Назначение персональной лицензии]);
* {blank}
+
"{dv} Внешние файловые хранилища" – разрешает использовать для хранения бинарных данных файлов внешние хранилища (подробности в разделе xref:External_Data_Storage.adoc[Настройка внешних хранилищ {dv}]). Также в лицензии должны быть дополнительные опции, определяющие разрешенные типы хранилищ:

** "{dv} Внешнее хранилище ФС" – разрешает использовать хранилище в файловой системе;
** "{dv} Внешнее хранилище MSSQL" – разрешает использовать хранилище во внешней БД Microsoft SQL;
** "{dv} Внешнее хранилище FileStream" – разрешает использовать хранилище FileStream внешней БД Microsoft SQL;
+
Если дополнительная опция "{dv} Внешние файловые хранилища" отсутствует, для хранения бинарных можно будет использовать только БД {dv} или FileStream базы данных {dv}.
* "{dv} Кластер AlwaysOn" – разрешает серверу {dv} работать с кластером баз данных SQL Server AlwaysOn (подробности в разделе xref:AlwaysOn.adoc[Размещение БД {dv} в группе доступности Microsoft SQL Server AlwaysOn]);
* "{dv} кэш-сервер" – разрешает использовать внешний кэш-сервер для хранения данных серверного кэша {dv}. Также в лицензии должна быть дополнительная опция, определяющая разрешенный тип кэш-сервера:
** "{dv} кеш-сервер Redis" – разрешает использовать кэш-сервер Redis;
* "{dv} Внешний полнотекстовый поиск" – разрешает использовать внешнюю систему полнотекстового поиска. Также в лицензии должна быть дополнительная опция, определяющая разрешенный тип системы полнотекстового поиска:
** "{dv} Внешний полнотекстовый поиск ElasticSearch" – разрешает использовать внешнюю систему полнотекстового поиска ElasticSearch;
+
Если дополнительная опция "{dv} Внешний полнотекстовый поиск" отсутствует, для полнотекстового поиска можно будет использовать только интегрированный в SQL Server полнотекстовый поиск.
* "{dv} Архивная база данных" – разрешает серверу {dv} вытеснять архивные карточки в отдельную (сателлитную) базу данных.
+
Если дополнительная опция "{dv} Архивная база данных" отсутствует, данные архивных карточек будут храниться в основной БД {dv}.

