= Лицензия

Для работы с модулем {pl} требуется лицензия на систему {dv} 5.5.

Возможность использования специальных функций {dv} определяется наличием в лицензии {dv} дополнительных опций:

{dv} СУБД PostgreSQL:: 
Разрешает работу с БД PostgreSQL.
+
{dv} Personal (VIP) Licenses:: 
Разрешает использование неконкурентных лицензий, назначаемых отдельным пользователям.
+
Подробнее в разделе xref:admin:manage-licenses.adoc#personalLicense[Назначение персональной лицензии]).
+
{dv} Внешние файловые хранилища:: 
Разрешает использовать для хранения бинарных данных файлов внешние хранилища
+
Подробнее в разделе xref:admin:storage.adoc[Настройка внешних хранилищ {dv}].
+
.В лицензии также должны быть дополнительные опции, определяющие разрешённые типы хранилищ:
+
{dv} Внешнее хранилище ФС:::
Разрешает использовать хранилище в файловой системе.
+
{dv} Внешнее хранилище MSSQL:::
Разрешает использовать хранилище во внешней БД Microsoft SQL.
+
{dv} Внешнее хранилище FileStream:::
Разрешает использовать хранилище FileStream внешней БД Microsoft SQL.
+
WARNING: Если дополнительная опция _{dv} Внешние файловые хранилища_ отсутствует, для хранения бинарных можно будет использовать только БД {dv} или FileStream базы данных {dv}.
+
{dv} Кластер AlwaysOn::
Разрешает серверу {dv} работать с кластером баз данных SQL Server AlwaysOn.
+
Подробнее в разделе xref:admin:db-always-on.adoc[Размещение БД {dv} в группе доступности Microsoft SQL Server AlwaysOn]).
+
{dv} кэш-сервер::
Разрешает использовать внешний кэш-сервер для хранения данных серверного кэша {dv}.
+
.В лицензии также должна быть дополнительная опция, определяющая разрешённый тип кэш-сервера:
{dv} кэш-сервер Redis:::
Разрешает использовать кэш-сервер Redis.
+
{dv} Внешний полнотекстовый поиск::
Разрешает использовать внешнюю систему полнотекстового поиска.
+
.В лицензии также должна быть дополнительная опция, определяющая разрешённый тип системы полнотекстового поиска:
+
{dv} Внешний полнотекстовый поиск {es}:::
Разрешает использовать внешнюю систему полнотекстового поиска {es}.
+
Если дополнительная опция {dv} Внешний полнотекстовый поиск отсутствует, для полнотекстового поиска можно будет использовать только интегрированный в SQL Server полнотекстовый поиск.
+
{dv} Архивная база данных::
Разрешает серверу {dv} вытеснять архивные карточки в отдельную (сателлитную) базу данных.
+
NOTE: Если дополнительная опция _{dv} Архивная база данных_ отсутствует, данные архивных карточек будут храниться в основной БД {dv}.
