= Назначение и функции

«Docsvision 5. Платформа» является [.dfn .term]_базовым модулем_ системы «Docsvision 5.5», который предоставляет [.dfn .term]_сервер Docsvision_, среду функционирования для других модулей (базовых и дополнительных) Docsvision, точку подключения для клиентских программ, а также инструменты для администрирования системы Docsvision.

Модуль не является автономным, он обеспечивает следующие функции:

* организация хранения и доступа к данным системы Docsvision;
* предоставление системных типов карточек (папок, настроек пользователя и др.);
* контроль доступа к данным на основе дискреционной модели безопасности;
* предоставление компонентов для установки, настройки и работы серверных частей других Модулей и Приложений Docsvision;
* предоставление точки подключения клиентов (программ);
* управление сессиями клиентов;
* кэширование данных;
* предоставление средств настройки системы Docsvision;
* и др.

*На уровень выше:* xref:../topics/General_information.adoc[Общие сведения о Модуле]
