= Требования к каналам связи

Администратор локальной сети должен обеспечить возможность подключения:

* с сервера Docsvision к СУБД с БД системы Docsvision. На компьютере с сервером Microsoft SQL должны быть открыты порты:
** 1433;
** 5022 и 5023 – если планируется использовать xref:AlwaysOn.adoc[AlwaysOn];
* с клиентских компьютеров к серверу Docsvision;
* с компьютера с сервером Docsvision к компьютеру с сервисом полнотекстового поиска, если сервис полнотекстового поиска установлен на отдельный компьютер.

Дополнительные требования, связанные с сетевой доступностью, могут быть предъявлены установленными Модулями Docsvision.

Компьютер с Модулем должен быть включен в домен Windows. Если компьютер с Модулем и клиентские компьютеры входят в разные домены, требуется наличие доверительных отношений между этими доменами, иначе NTLM-аутентификация будет невозможна (потребуется явный ввод имени пользователя и пароля при входе в систему).

*На уровень выше:* xref:../topics/Required_resources.adoc[Необходимые ресурсы]
