= Требования учетной записи сервиса полнотекстового индексирования

Перечисленные права должны быть предоставлены учетной записи службы *{fts-new}*.

include::partial$chunks.adoc[tags=system-accounts]

== Требования на уровне ОС сервера

. Принадлежность к группе безопасности *{dv-admins-serv}*.
. Разрешение на запись в файл журнала (если ведется).

== Требования на уровне СУБД

[WARNING]
====
* Если БД подключена с использованием SQL-аутентификации, данные требования предъявляются к учетной записи, которая указана при подключении БД к {dv}.
* Если БД подключена с использованием аутентификации Windows, данные требования предъявляются к учетной записи, от имени которой запущена служба _{fts-new}_.
====

=== Требования для всех баз данных {dv}:

. Роль _db_owner_.
. `EXECUTE` для хранимых процедур, которые начинаются с префиксов *dvsys_*, *dvsp_* и *dvreport_* (используются для обработки данных).
. `SELECT`, `INSERT`, `UPDATE`, `DELETE` на всех таблицах базы данных, которые начинаются с префиксов *dvsys_* и *dvtable_*.

=== Требования для СУБД Microsoft SQL Server

. `VIEW`, `CREATE TABLE`, `CREATE PROCEDURE`, `CREATE FUNCTION` и `ALTER SERVER STATE` на уровне базы данных, `ALTER DATABASE`, а также `ALTER` для схемы dbo.
. На системную базу данных _tempdb_: роль _db_owner_.

=== Требования для СУБД PostgreSQL:

. Права пользователя _postgres_.
