= Необходимое программное обеспечение

[#serverRequirements]
== Требования серверной части модуля

.Операционная система:
* Microsoft Windows Server 2019 (Standard, DataCenter).
* Microsoft Windows Server 2016 (Standard, DataCenter).
* Microsoft Windows Server 2012 R2 (Standard, DataCenter).
* Microsoft Windows Server 2012 (Standard, DataCenter).
* _Только для демонстрационного сервера:_ Windows 8/8.1 (64-разрядная) или Windows 10 (64-разрядная) с поддержкой ввода в домен.

.Обязательное программное обеспечение:
. IIS версий 7.5, 8.0, 8.5 или 10. В настройках сервера должна быть включена поддержка ASP.NET 4.0 в IIS.
. Microsoft .NET Framework 4.7.footnote:[Microsoft .NET Framework 4.6.1, если не требуется поддержка СУБД PostgreSQL] или выше.
. Microsoft .NET Framework 3.5 SP1.

== Требования клиентской части модуля

.Операционная система:
* Microsoft Windows 7 SP 1 (Enterprise, Professional, Ultimate).
* Microsoft Windows 8/8.1 (Pro, Enterprise)footnote:[Работа в ОС Windows 8 поддерживается только в режиме "Рабочего стола". Работа в режиме Metro, в том числе в Metro-Internet Explorer, не поддерживается.].
* Microsoft Windows 10 (Pro, Enterprise).
* Или любая ОС, указанная в требованиях <<serverRequirements,серверной части модуля>>.

.Обязательное программное обеспечение:
. Microsoft .NET Framework 4.6.1.
