= Требования учетной записи сервиса полнотекстового индексирования

Перечисленные права должны быть предоставлены учетной записи службы «Docsvision 5.5 Full-Text Indexing Service».

. Требования на уровне ОС сервера:
[loweralpha]
.. Принадлежность к группе безопасности «DocsVision Administrators».
.. Разрешение на запись в файл журнала (если ведется).
. Требования на уровне СУБД (см. важное условие ниже):
* для СУБД Microsoft SQL Server:
[loweralpha]
.. VIEW, CREATE TABLE, CREATE PROCEDURE, CREATE FUNCTION и ALTER SERVER STATE на уровне базы данных, ALTER DATABASE, а также ALTER для схемы dbo.
.. На системную базу данных [.dfn .term]_tempdb_: роль db_owner.
.. На все базы данных Docsvision:
[lowerroman]
... Роль db_owner;
... EXECUTE для хранимых процедур, которые начинаются с префиксов dvsys_, dvsp_ и dvreport_ (используются для обработки данных);
... SELECT, INSERT, UPDATE, DELETE на всех таблицах базы данных, которые начинаются с префиксов dvsys_ и dvtable_.
* для СУБД PostgreSQL:
[loweralpha]
.. Права пользователя «postgres».
+
*Обратите внимание:* требования, перечисленные в п. 2, предъявляются к учетной записи, с которой служба «Docsvision 5.5 Full-Text Indexing Service» обращается к БД Docsvision:

* если БД подключена с использованием SQL-аутентификации, то данные требования предъявляются к учетной записи, которая указана при подключении БД к Docsvision;
* если БД подключена с использованием аутентификации Windows, то данные требования предъявляются к учетной записи, от имени которой запущена служба «Docsvision 5.5 Full-Text Indexing Service».

*На уровень выше:* xref:../topics/Appendix_B.adoc[Приложение B. Требования сервисов Docsvision]
