= Рекомендации к аппаратному обеспечению сервера Microsoft SQL

В таблице приведены рекомендации к аппаратному обеспечению сервера Microsoft SQL в зависимости от планируемого числа одновременно работающих с системой {dv} пользователей.

.[.table--title-label]##Table 1. ##[.title]##Рекомендуемые аппаратные характеристики сервера СУБД##
[width="100%",cols="30%,70%",options="header"]
|===
|Число пользователей |Требования
|до 100 |См. требования в пункте xref:Required_resources_hardware.adoc[Необходимое техническое обеспечение] (до 100 пользователей)
|100-250 a|
Процессор: Intel Xeon E3/E5, 8 ядер

Оперативная память: от 16 Гб

Жесткий диск: размер определяется объемом базы данных, не менее 80 IOPS в операциях произвольного чтения

|250-500 a|
Процессор: Intel Xeon E5, 16 ядер

Оперативная память: от 32 Гб

Жесткий диск: размер определяется объемом базы данных, не менее 140 IOPS в операциях произвольного чтения

|500-1000 a|
Процессор: Intel Xeon E5/E7, 32 ядра

Оперативная память (RAM): от 64 Гб

Жесткий диск: размер определяется объемом базы данных, не менее 500 IOPS в операциях произвольного чтения

|1000-5000 a|
Процессор: Intel Xeon E7, 48 ядер

Оперативная память (RAM): от 128 Гб

Жесткий диск: размер определяется объемом базы данных, не менее 1000 IOPS в операциях произвольного чтения

|Более 5000 |Рассчитывается индивидуально
|===

