= Требования для отдельной установки сервиса полнотекстового индексирования

Данные требования предъявляются сервисом полнотекстового индексирования для отдельной от сервера {dv} установки.

include::partial$chunks.adoc[tags=system-accounts]

include::partial$summingRequirements.adoc[]

[cols=",,",options="header"]
|===
|Аппаратные требования |Программные требования |Лицензия
a|*Процессор*: 2 ГГц и выше, 4 ядра.

*Оперативная память*: от 4 Гб.

*Система хранения данных*: от 120 Гб.
include::partial$excerpts.adoc[tags=SSD]

NOTE: Если планируется использовать полнотекстовый поиск {es}, ознакомьтесь с требованиями в xref:requirements-hardware.adoc#elastic[данном] разделе.

a|.Операционная система:

См. требования в разделе "xref:requirements-software.adoc#linux[Необходимое программное обеспечение]"

*Обязательное программное обеспечение:*

Microsoft .NET Framework 4.7footnote:[Microsoft .NET Framework 4.6.1, если не требуется поддержка СУБД PostgreSQL].

|Для использования функции _Интеллектуальный поиск_ требуется дополнительная опция лицензии, см. документацию модуля "xref:6.1@webclient:ROOT:requirements-license.adoc[]".
|===
