= Структура модуля

Модуль {pl} состоит из двух частей:

. Серверная часть включает следующие элементы:
[loweralpha]
.. Веб-приложение "DocsVision" в IIS – предоставляет функции сервера {dv} клиентам, подключающимся по протоколу HTTP (+SOAP): предоставление доступа к данным, поддержка целостности данных, обеспечение проверки прав доступа, и др.
.. Службы Windows:
* "{dv} 5.5 Storage Server" – предоставляет функции сервера {dv} клиентам, подключающимся по протоколу WCF;
* "{dv} 5.5 Full-text indexing Service" (сервис полнотекстового индексирования) – передает данные, требующие построения полнотекстовых индексов, в Microsoft SQL Server или во внешнюю систему полнотекстового поиска "Elasticsearch";
* "{dv} 5.5 File Service" (файловый сервис {dv}) – выполняет отложенные операции удаления бинарных данных файлов из внешних хранилищ, и перемещает данные между хранилищами.
.. Системные типы карточек: _Карточка папок_, _Справочник мандатной безопасности_, _Системные настройки_ и др.
.. Хранимые процедуры для БД.
.. Пакет установки клиентской части модуля {pl} и др.
. Клиентская часть (для установки на компьютеры пользователей {dv}) включает следующие элементы:
[loweralpha]
.. Библиотеки DLL с клиентским API {dv}.
.. Клиентские компоненты системных карточек.
