[[ariaid-title1]]
== Структура Модуля

Модуль «Платформа» состоит из двух частей:

. Серверная часть включает следующие элементы:
[loweralpha]
.. Веб-приложение «DocsVision» в IIS – предоставляет функции сервера Docsvision клиентам, подключающимся по протоколу HTTP (+SOAP): предоставление доступа к данным, поддержка целостности данных, обеспечение проверки прав доступа, и др.
.. Службы Windows:
* «Docsvision 5.5 Storage Server» – предоставляет функции сервера Docsvision клиентам, подключающимся по протоколу WCF;
* «Docsvision 5.5 Full-text indexing Service» (сервис полнотекстового индексирования) – передает данные, требующие построения полнотекстовых индексов, в Microsoft SQL Server или во внешнюю систему полнотекстового поиска «Elasticsearch»;
* «Docsvision 5.5 File Service» (файловый сервис Docsvision) – выполняет отложенные операции удаления бинарных данных файлов из внешних хранилищ, и перемещает данные между хранилищами.
.. Системные типы карточек: [.dfn .term]_Карточка папок_, [.dfn .term]_Справочник мандатной безопасности_, [.dfn .term]_Системные настройки_ и др.
.. Хранимые процедуры для БД.
.. Пакет установки клиентской части модуля «Платформа» и др.
. Клиентская часть (для установки на компьютеры пользователей Docsvision) включает следующие элементы:
[loweralpha]
.. Библиотеки DLL с клиентским API Docsvision.
.. Клиентские компоненты системных карточек.
