= Создание отказоустойчивых кластеров с функцией AlwaysOn

[WARNING]
====
Для использования функциональности "отказоустойчивый кластер AlwaysOn" дополнительная опция лицензии не требуется.

Включать флаг `*Использовать AlwaysOn*` также не требуется.
====

Отказоустойчивый кластер AlwaysOn напрямую не поддерживается. Однако, использование данной функциональности технически возможно, но вызовет ряд трудностей.

В {dv} из соображений быстродействия часть таблиц БД вынесены из основной базы и хранятся в `TempDB`. `TempDB` используется для хранения большинства временных данных, включая курсоры представлений, результаты поисков, и т.п. При необходимости данный режим по умолчанию может быть изменён.

.Если требуется сократить ручное вмешательство при аварийных переключениях и сохранить между узлами данные из `tempdb`, используйте другие варианты конфигурации баз данных:
* Разместите резервные данные в сателлите *_Metadata*. В таком случае потребуется также настроить отражение этой базы вместе с основной базой.
* Включите режим размещения всего в основной базе (такая конфигурация использовалась до версии 5.4 включительно).

WARNING: Обратите внимание, что это менее производительные режимы, которые приведут к снижению производительности!
