:ms: Microsoft
:mssql: {mssql} Server Management Studio
:wf: Workflow

= Резервное копирование базы данных

Система {dv} сохраняет информацию о карточках в SQL базе данных. Чтобы защитить данные от повреждения, удаления и в других случаях можно создать резервную копию БД. В данном разделе приведена инструкция по резервному копированию баз данных <<mssql,{mssql}>> и <<pgsql,{pgsql}>>, а также инструкция по <<porting,переносу БД на другой сервер>>

При восстановлении БД из резервной копии под другим именем обратите внимание на рекомендации в пункте xref:db-rename.adoc[].

[#mssql]
== {mssql}

[#mssql-create]
=== Создание резервной копии БД {mssql}

include::admin:partial$excerpts.adoc[tags=backupDb]

. Откройте {mssql}.
. Подключитесь к серверу БД, указав учётные данные.
. Найдите БД, для которой требуется создать резервную копию в списке баз данных.
. Нажмите правой кнопкой на базу данных, выберите *Задачи* > *Создать резервную копию*.
. Выберите желаемые настройки резервного копирования и нажмите *ОК*.

[#mssql-restore]
=== Восстановление БД из резервной копии {mssql}

include::admin:partial$excerpts.adoc[tags=restoreDb]

. Откройте {mssql}.
. В списке доступных баз данных выберите БД, которую нужно восстановить и вызовите контекстное меню правой кнопкой мыши.
. Выберите *Задачи > Отсоединить*.
. В появившемся окне поставьте флаг в колонке _Удалить соединения_ и нажмите *ОК*.
. Затем, в главном меню {mssql} поднимитесь вверх, наведите курсор на папку *Базы данных* и вызовите контекстное меню правой кнопкой мыши.
. В контекстном меню выберите *Восстановить базу данных*.
. Напротив слов *База данных* в раскрывающемся списке выберите БД, которую необходимо восстановить.
. Затем выберите нужные настройки и нажмите *ОК*.

*Подробнее о создании резервных копий в {mssql}* можно почитать на сайте https://docs.microsoft.com/ru-ru/sql/relational-databases/backup-restore/create-a-full-database-backup-sql-server?view=sql-server-ver15[Docs.Microsoft.com].

[#pgsql]
== {pg} SQL

[#pgsql-create]
=== Создание резервной копии БД {pg} SQL

include::admin:partial$excerpts.adoc[tags=backupDb]

Для создания резервной копии базы данных {pgsql} можно воспользоваться утилитой *pg_dump*.

Базовый синтаксис для запуска резервного копирования при помощи *pg_dump* следующий:

----
pg_dump имя_базы > файл_дампа
----

WARNING: Команду резервного копирования обычно требуется запускать с правами суперпользователя

Чтобы указать адрес сервера БД для резервного копирования можно использовать параметры `-h сервер` и `-p порт`. По умолчанию *pg_dump* использует в качестве сервера localhost или значения переменных среды: `PGHOST` для адреса сервера и `PGPORT` для порта. Когда переменные не указаны, используются значения, указанные во время компиляции.

В качестве учётных данных для подключения к БД *pg_dump* использует имя пользователя текущего пользователя операционной системы. Передать учётные данные, отличающиеся от текущих можно при помощи параметра `-U пользователь`. Для указания учётных данных можно также использовать переменную среды `PGUSER`.

[#pgsql-restore]
=== Восстановление из резервной копии БД {pg} SQL

include::admin:partial$excerpts.adoc[tags=restoreDb]

.Чтобы восстановить БД {pgsql} из резервной копии при помощи можно использовать утилиту *psql* со следующим синтаксисом:
----
psql имя_базы < файл_дампа
----

В данном случае файл дампа -- это созданная ранее при помощи *pg_dump* резервная копия.

Утилита *psql* принимает те же параметры для указания сервера, порта и учётных данных, что и *pg_dump*.

*Подробнее о создании резервных копий в {pgsql}* можно почитать по ссылкам: https://postgrespro.ru/docs/postgresql/9.6/backup[PostgresPro], https://habr.com/ru/post/222311/[Хабр].

[#porting]
== Перенос БД на другой сервер

Если требуется перенести созданную резервную копию базы данных на другой сервер, выполните следующие действия:

. Создайте резервную копию базы данных на текущем сервере БД (исходный сервер) согласно инструкции для <<mssql, {mssql}>> или <<pgsql,{pgsql}>>.

. Остановите службу {wf} на сервере для переноса БД (целевом сервере).

. Восстановите БД из резервной копии на целевом SQL-сервере.

. Очистите таблицу `B4A2559B-45FD-4ABA-919F-0F170CCDDB5D` от настроек исходного сервера.

. Очистите таблицу `dvsys_sessions` от старых сессий.

. Актуализируйте значения в таблице `dvsys_settings`. Убедитесь, что в таблице отсутствуют неправильные адреса.

. Запустите службу {wf} на целевом сервере.

. Запустите _{cns}_ на целевом сервере.

. Проверьте текущие настройки и выполните недостающие настройки, если необходимо.

. Запустите консоль настройки {wc}. Актуализируйте адрес подключения и базы данных.

. На компьютере с серверными частями модулей откройте редактор реестра. В редакторе реестра перейдите на ветку `{hklm}\SOFTWARE\DocsVision\Workflow` и убедитесь, что ссылки на другие серверы отсутствуют. Вам нужно проверить параметры: _SiteUrl_ и _SoapServiceUrl_.

.Важная информация при создании резервных копий БД
****
Если целевой сервер является копией виртуального сервера, необходимо в реестре найти ключи со значениями, указывающими на сервер и базу данных и заменить значения ключей на актуальные. В противном случае {wincl} при запуске не сможет обнаружить новый сервер и БД.

В новой БД могут быть установлены уведомления с мониторингом или может потребоваться отключить уведомления для тестовой БД. В таком случае необходимо в карточке сотрудника для всех пользователей очистить поле электронной почты или остановить все БП уведомлений.

Восстанавливать БД на SQL сервере и подключать на сервере приложений обязательно под другим именем. Несоблюдение этого требования приведёт к проблемам в работе службы *{wfs-new}*.
****

include::db-satellite.adoc[tags=copy]
