= Изменить режим формирования представлений в БД

Представления, с помощью которых в {dv} отображается содержимое папок, представляют собой специальным образом сформированные таблицы в базе данных {dv}.

Часть данных для работы представлений формируется заданием *ObjectValidation* базы данных, на время выполнения которого напрямую влияет количество пользователей и представлений в системе {dv}.

Администратор может изменить режим формирования представлений: формировать представления предварительно заданием *ObjectValidation* или формировать представления при обращении пользователей. Во втором случае на первое открытие представлений потребуется больше времени.

Чтобы изменить режим формирования представлений, выполните в базе данных один из следующих скриптов:

.Скрипт для формирования представлений заданием "ObjectValidation".
[%collapsible]
====
[source,sql]
----
decalre @value bit = 1
exec dvsys_setting_set 'CreateViewKeysetTablesInsideObjectValidation', @value
----
====

.Скрипт для формирования представлений при обращении.
[%collapsible]
====
[source]
----
decalre @value bit = 0
exec dvsys_setting_set 'CreateViewKeysetTablesInsideObjectValidation', @value
----
====
