= Изменить расположение пользовательской документации

При обращении к документации из программ {wincl} и {wc}, пользователь по умолчанию будет направлен на https://docsvision.com[сайт компании ДоксВижн].

При необходимости администратор может разместить документы на ресурсах своей организации. Для этого необходимо изменить шаблон, по которому определяется расположение документации. Расположение пользовательской документации можно изменить в конфигурационном файле модуля {pl} в параметре `"HelpUrl"` или через графический интерфейс {of-mc}, см. подробнее "xref:mgmtconsole:user:server-settings.adoc#docs-url[Адрес сайта документации]".

[source,json]
----
{
  "DocsVision": {
    "Platform": {
      "Server": {
        "Site": {
          "HelpUrl": "http://help.docsvision.com/{client}/{version}",
          "InstallLogPath": null, <.>
          "InstallAction": 0, <.>
          "InstallUILevel": 0, <.>
          "InstallScope": 0  <.>
        }
      }
    }
  }
}
----
<.> Папка журналов установки.
<.> Установка решений: `0` -- по умолчанию, `1` -- не инсталлировать, `2` -- полная установка, `3` -- режим Advertise.
<.> Интерфейс установки: `0` -- по умолчанию, `1` -- не отображать, `2` -- минимальный интерфейс, `3` -- сокращённый интерфейс, `4` -- полный интерфейс.
<.> Область установки: `0` -- для текущего пользователя, `1` -- для всех пользователей, `2` -- определять автоматически, при наличии полномочий устанавливается для всех пользователей, иначе только для текущего пользователя.

[#templates]
== Шаблоны расположения документации

.В шаблоне могут быть использованы переменные:
* `\{client}` -- псевдоним клиентской программы, который может приобретать значения:
** `winclient` -- для {wincl}а.
** `webclient` -- для {wc}а.
+
[NOTE]
====
Другие клиентские приложения не поддерживают настройку, определяющую расположение документации.
====
+
* `\{version}` -- версия клиентской программы.

Таким образом фактический стандартный адрес документации, к примеру, для модуля {pl} версии {page-version} будет следующим: `\http://help.docsvision.com/platform/{page-version}/`.

WARNING: Для всех клиентских программ используется общий шаблон, поэтому размещать документацию {wincl}а и {wc}а следует на одном сайте.

[#deploy-docs]
== Как развернуть документацию из исходного кода

Новая документация {dv} разворачивается с помощью https://docs.antora.org/[генератора статических сайтов Antora]. Для первой сборки сайта потребуется доступ к репозиториям документации {dv}, https://github.com/Docsvision?q=antora-&type=all&language=&sort=[расположенным на GitHub]. Репозитории документации обозначены префиксом `antora-`. Полный список источников указан в файле `https://github.com/Docsvision/antora-playbook/blob/083db793049a159db9b4c526ce5b1f3a58870c39/antora-playbook.yml#L24[antora-playbook.yml]` репозитория antora-playbook.

Документация может быть развёрнута локально, в таком случае адрес документации может быть изменён.

[#build-site]
=== Сборка сайта

.Требования для сборки сайта:
* Установлен git.
* Установлен Node.js версии, указанной в разделе "https://docs.antora.org/antora/latest/install/windows-requirements/[Требования]" на сайте документации Antora.
* Доступ к сайту Github или иной доступ к репозиториям исходного кода документации.
* Доступ к локальной копии репозитория https://github.com/Docsvision/antora-playbook/[Docsvision/antora-playbook/].

. Откройте командную строку с расположением в корне репозитория "Docsvision/antora-playbook/"
. Установите Antora командой:
+
 npm i
+
. Запустите сборку сайта при помощи Antora, выполнив следующую команду:
+
 npx antora antora-playbook.yml
+
. Файлы сайта будут расположены в папке `wwwroot`.

[#view]
=== Просмотр сайта

.Сайт можно просматривать:
** Локально -- нажмите на сгенерированные html-файлы, расположенные в папке `wwwroot`.
** С простого http-сервера -- выполните шаги, https://docs.antora.org/antora/latest/preview-site/#run-a-local-server-optional[указанные в инструкции Antora].

[#limitations]
=== Ограничения

.После сборки сайта некоторые функции окажутся недоступны:
* Поиск по сайту.
* Просмотр страниц накопительных обновлений.

Чтобы воспользоваться функциями локального (офлайн) поиска, рекомендуется использовать расширение Antora Lunr Search. Подробная инструкция по разворачиванию приведена https://www.npmjs.com/package/antora-lunr[по ссылке].
