= Настроить протоколирование работы файлового сервиса

Работа файлового сервиса {dv} (служба *{fss-new}*) протоколируется со следующими параметрами по умолчанию:

.Если для сервера {dv} включено протоколирование работы:
* Файл журнала: `/var/log/docsvision/fileservice/`.
* Уровень логирования: `уровень-логирования-сервера`.

// .Если для сервера {dv} не включено протоколирование работы:
// * Файл журнала: `C:\Program Files (x86)\Docsvision\Platform\FileService.log`.
// * Уровень логирования: только ошибки.

.Чтобы изменить настройки:
// . Добавьте в реестр ОС сервера {dv} параметры:
// * `{hklm-dv}\Platform\Server\FileServiceLogFile` -- полный путь с именем файла журнала.
// +
// Тип параметра -- строковый.
// +
// * `{hklm-dv}\Platform\Server\FileServiceTraceLevel` -- уровень логирования.
// +
// Тип параметра -- `DWORD32`.
// +
. Отредактируйте параметр `"Logging":` в конфигурационном файле файлового сервиса `/usr/lib/docsvision/fileservice/appsettings.json`.
+
.Возможные уровни логирования:
** `1` -- только ошибки.
** `3` -- ошибки и информационные сообщения.
+
. Перезапустите файловый сервис {dv}.
+
[WARNING]
====
Учетная запись файлового сервиса {dv} должна обладать правами на создание, изменение и чтение файла журнала.
====

Журнал формируется, если в конфигурационном файле службы *{fss-new}* указана строка подключения к БД {dv} в параметре `"Databases":`. Уровни журналирования настраиваются внутри секции `nlog`. Ниже приведён пример, где уровень журналирования указывается словом, а не цифрой, `minlevel="Warn"`:

.Фрагмент конфигурационного файла службы {fss-new}:
[source,json]
----
{
  "DocsVision": {
    "Platform": {
      "Server": {
        "Databases": {
          "alias": "Initial Catalog=DBname; Data Source=database.server.com; User ID=user; Password=qwerty" <.>
        }
      }
    }
  },
  "NLog": {
    "targets": {
      "logFile": {
        "type": "File",
        "fileName": "${gdc:baseLogFolder}/docsvision/fileservice/${shortdate}.log",
        "layout": "${longdate}|${event-properties:item=EventId_Id}|${uppercase:${level}}|${logger}|${message} ${exception:format=tostring}"
      }
    },
    "rules": [
      {
        "logger": "*",
        "minLevel": "Warn", <.>
        "writeTo": "logFile"
      }
    ]
  },
}
----
<.> Строка подключения к базе данных {dv}.
<.> Уровень журналирования "Warn".

Дополнительная информация по настройке журналирования приведена https://nlog-project.org[на сайте] компонента NLog.
