= Журналы системы

В системе {dv} имеется ряд журналов, которые используются для сбора информации о процессе установки и работы системы:

* <<server,Журнал работы сервера>>.
* <<client,Журналы установки клиентских компонентов>>.
* <<console,Журнал сообщений "Консоли настройки {dv}">>.
* <<search,Журнал сообщений сервиса полнотекстового поиска>>.
* <<file,Журнал работы файлового сервиса>>.

// Если любой из файлов журнала не получается сохранить по указанному в настройках пути, он будет сохранён в папке `%localappdata%\Docsvision\Logs`. Путь к папке может отличаться в зависимости от пользователя, под которым запущены службы или серверная консоль.

[#server]
== Журнал работы сервера

Данный журнал содержит информацию о работе сервера {dv}. Журнал сервера является средством диагностики при возникновении нештатных ситуаций и предназначен для передачи в службу технической поддержки {dv}.

Путь к журналу указывается в конфигурационном файле модуля {pl}, см. раздел "xref:admin:config-platform.adoc[]" в секции `"LogFile"`.

По умолчанию журнал работы сервера сохраняется в папку `/var/log/docsvision/dvappserver.log`.

// .Если доступ на запись в директорию по умолчанию отсутствует, будет формироваться два журнала сервера:
// * В журнал по пути `C:\Users\%user%\AppData\Local\DocsVision\Logs\Server` будут попадать все ошибки службы *{sss}*. В данном случае `%user%` -- пользователь, от имени которого запущена служба *{sss}*.
// * В журнал по пути `C:\Windows\System32\config\systemprofile\AppData\Local\Docsvision\Logs\Server` будут попадать ошибки web-сервиса IIS.

[NOTE]
====
В системном журнале и журнале приложений может встречаться ошибка `Unexpected error: The file '/docsvision/StorageServer/Fetch.aspx' does not exist.`

Ошибка возникает из-за наличия модуля _Конструктор отчетов_, несовместимого с {dv} текущей версии. Обработка запросов от данного модуля будет отключена.
====

[#client]
== Журналы установки клиентских компонентов

В журналах установки клиентских компонентов фиксируются события, возникающие в процессе установки клиентской части модулей {dv}.

Журнал формируется отдельно для каждого из устанавливаемых клиентских компонентов и сохраняется в текстовый файл.

Путь к папке для хранения журналов всех установленных клиентских компонентов указывается в программе _{cns}_ в параметре *Папка журналов установки* раздела xref:config-client.adoc[Настройка клиентской части].

Просмотреть журнал можно, открыв файл в текстовом редакторе.

[#search]
== Журнал сообщений сервиса полнотекстового поиска

xref:search-logging.adoc[Данный журнал] содержит информацию о работе сервиса полнотекстового индексирования {dv}.

По умолчанию журналы сообщений сервиса полнотекстового поиска сохраняется в директории `/var/log/docsvision/fulltextservice.log`.

[#console]
== Журнал сообщений "Консоли настройки {dv}"

{cns} устанавливается на машину Windows. По умолчанию журнал располагается по адресу `Каталог-установки-серверной-части-модуля-{pl}\Logs\ServerConsole.log`

.Ведение журнала можно отключить в настройках:
. Откройте _{cns}_.
. В меню выберите menu:Инструменты[Настройки...].
. В окне _Общие настройки_ поставьте флаг `*Журналировать операции консоли настройки*` и укажите путь к файлу журнала в поле _Файл журнала_.

В журнале ведётся протоколирование событий программы _{cns}_ и всех операций, выполняемых через программу.

[#file]
== Журнал работы файлового сервиса

В данный журнал сохраняется информация об ошибках работы файлового сервиса {dv}, а также информационные сообщения (если включено).

Журнал сервера является средством диагностики при возникновении нештатных ситуаций и предназначен для передачи в службу технической поддержки {dv}.

По умолчанию журнал сохраняется в каталог `/var/log/docsvision/fuileservice.log`. Подробнее см. в пункте xref:file-service-logging.adoc[Настройка протоколирования работы файлового сервиса {dv}].
