= Журналы системы

В системе {dv} имеется ряд журналов, которые используются для сбора информации о процессе установки и работы системы:

* <<server,Журнал работы сервера>>.
* <<client,Журналы установки клиентских компонентов>>.
* <<console,Журнал сообщений "Консоли настройки {dv}">>.
* <<search,Журнал сообщений сервиса полнотекстового поиска>>.
* <<file,Журнал работы файлового сервиса>>.

// Если любой из файлов журнала не получается сохранить по указанному в настройках пути, он будет сохранён в папке `%localappdata%\Docsvision\Logs`. Путь к папке может отличаться в зависимости от пользователя, под которым запущены службы или серверная консоль.

Настройки журналирования указываются в конфигурационном файле соответствующего сервиса.

[#server]
== Журнал работы сервера

Данный журнал содержит информацию о работе сервера {dv}. Журнал сервера является средством диагностики при возникновении нештатных ситуаций и предназначен для передачи в службу технической поддержки {dv}.

По умолчанию журнал сервиса сохраняется в папку `/var/log/docsvision/appserver/dvappserver.log`. Путь к журналу и уровень журналирования можно настроить в конфигурационном файле модуля {pl}, подробнее работа с конфигурационным файлом описана в разделе "xref:admin:config-platform.adoc[]"

Пример настройки уровня журналирования приведён ниже.

.Фрагмент конфигурационного файла {sss-new}:
[source,json]
----
{
  "DocsVision": {
    "Platform": {
      "Server": {
        "TraceLevel": 1 <.>
        "LogFile": "/var/log/docsvision/appserver/dvappserver.log" <.>
      }
    }
  }
}
----
<.> Уровень журналирования: `0` -- журналирование не ведётся, `1` -- Error, `2` -- Warning, `3` -- Info, `4` -- Verbose. Если значение не задано, по умолчанию используется "Error".
<.> Путь до файла журнала. По умолчанию `/var/log/docsvision/appserver/dvappserver.log`.

[NOTE]
====
В системном журнале и журнале приложений может встречаться ошибка `Unexpected error: The file '/docsvision/StorageServer/Fetch.aspx' does not exist.`

Ошибка возникает из-за наличия модуля _Конструктор отчетов_, несовместимого с {dv} текущей версии. Обработка запросов от данного модуля будет отключена.
====

[#client]
== Журналы установки клиентских компонентов

В журналах установки клиентских компонентов фиксируются события, возникающие в процессе установки клиентской части модулей {dv}.

Журнал формируется отдельно для каждого из устанавливаемых клиентских компонентов и сохраняется в текстовый файл.

Путь к папке для хранения журналов всех установленных клиентских компонентов указывается в программе _{cns}_ в параметре *Папка журналов установки* раздела "xref:config-client.adoc[Настройка клиентской части]".

Просмотреть журнал можно, открыв файл в текстовом редакторе.

[#search]
== Журнал сообщений сервиса полнотекстового поиска

Данный журнал содержит информацию о работе сервиса полнотекстового индексирования {dv}.

По умолчанию журналы сообщений сервиса полнотекстового поиска сохраняется в директории `/var/log/docsvision/fulltextservice.log`.

Подробнее настройка журналирования полнотекстового поиска описана в разделе "xref:search-logging.adoc[]".

[#console]
== Журнал сообщений "Консоли настройки {dv}"

{cns} устанавливается на машину Windows. По умолчанию журнал располагается по адресу `Каталог-установки-серверной-части-модуля-{pl}\Logs\ServerConsole.log`

.Ведение журнала можно отключить в настройках:
. Откройте _{cns}_.
. В меню выберите menu:Инструменты[Настройки...].
. В окне _Общие настройки_ поставьте флаг `*Журналировать операции консоли настройки*` и укажите путь к файлу журнала в поле _Файл журнала_.

В журнале ведётся протоколирование событий программы _{cns}_ и всех операций, выполняемых через программу.

[#file]
== Журнал работы файлового сервиса

В данный журнал сохраняется информация об ошибках работы файлового сервиса {dv}, а также информационные сообщения (если включено).

Журнал сервера является средством диагностики при возникновении нештатных ситуаций и предназначен для передачи в службу технической поддержки {dv}. По умолчанию журнал сервиса сохраняется в папку `/var/log/docsvision/fileservice`. Путь к журналу и уровень журналирования можно настроить в конфигурационном файле модуля {pl}.

.Фрагмент конфигурационного файла {fss-new}:
[source,json]
----
  "NLog": {
    "targets": {
      "logFile": {
        "type": "File",
        "fileName": "${gdc:baseLogFolder}/docsvision/fileservice/${shortdate}.log", <.>
        "layout": "${longdate}|${event-properties:item=EventId_Id}|${uppercase:${level}}|${logger}|${message} ${exception:format=tostring}"
      }
    },
    "rules": [
      {
        "logger": "*",
        "minLevel": "Warn", <.>
        "writeTo": "logFile"
      }
    ]
  },
----
<.> Путь к файлу журнала настраивается в параметре `\{gdc:baseLogFolder}`. По умолчанию используется каталог `/var/log/docsvision/fileservice`.
<.> Уровень журналирования, по умолчанию используется `Warn`.

Подробнее настройка журналирования *{fss-new}* описана в разделе "xref:file-service-logging.adoc[Настройка протоколирования работы файлового сервиса {dv}]".
