= Настроить кэш-сервер Redis

Важным условием для корректной работы системы {dv}, включающей несколько процессов сервера {dv}, является использование всеми процессами общего серверного кэша. Рассинхронизация кэша может стать причиной появления неактуальных данных и других ошибок. В качестве хранилища распределенного кэша в {dv} выступает кэш-сервер Redis.

[WARNING]
====
Для работы с Redis лицензия {dv} должна содержать опцию _{dv} кэш-сервер Redis_. Отсутствие лицензии приведёт к ошибке в работе сервера {dv}.

Кэш-сервер Redis не поддерживает работу в ОС Microsoft Windows.
====

[NOTE]
====
Инструкцию по установке Redis см. в документации к https://redis.io/docs/getting-started/installation/[кэш-серверу]. Системные требования Redis зависят от желаемой производительности, ориентиры представлены в статье https://web.archive.org/web/20241007143629/https://redis.io/docs/latest/operate/oss_and_stack/management/optimization/benchmarks/[How fast is Redis?], и требованиях https://web.archive.org/web/20240318121627/https://docs.redis.com/latest/rs/installing-upgrading/install/plan-deployment/hardware-requirements/[Redislabs].
====

== Требования к настройке Redis

После установки Redis измените настройки в конфигурационном файле `redis.conf`:

. Отключите сохранение резервных копий данных на диск, закомментировав следующие строки:
+
[source]
----
save 900 1
save 300 10
save 60 10000
----
+
. Затем установите значение параметра `appendonly` в *no* (по умолчанию).
. Измените политику перезаписи данных при нехватке памяти на `allkeys-lru` (удаление наименее используемых данных):
+
[source]
----
maxmemory-policy allkeys-lru
----
+
. Чтобы избежать ошибок при подключении, привяжите адрес в конфигурационном файле Redis:
+
 sudo nano /etc/redis/redis.conf
+
В конце строки `bind 127.0.0.1 ::1` укажите корректный адрес кэш-сервера.
+
. Перезапустите Redis:
+
 sudo systemctl restart redis-server.service
+
. Подключение должно работать корректно. Проверить, что сервер обращается к нужному адресу можно следующей командой:
+
 ss -tunlp | grep :6379

=== Подключение Redis к {dv}

. Откройте _{cns}_
. Перейдите в раздел настроек menu:Настройки сервера[Базы данных].
. Выберите настраиваемую базу данных, при работе с которой сервер будет кэшировать данные в Redis, и нажмите на кнопку *Настройки*.
+
****
Будет открыто окно *Свойства и управление базой данных*.
****
+
. Перейдите на вкладку xref:db-config.adoc#caching[Настройки кэширования].
. Выберите в списке _Провайдер_ значение *_Redis_*. Будет разблокировано поле _Строка подключения_.
. Введите в поле _Строка подключения_ адрес и порт для подключения к компьютеру с Redis в формате `IP-адрес:Порт`. По умолчанию Redis использует порт `6379`.
+
WARNING: Сетевые политики должны разрешать подключения с серверов {dv} к Redis.
+
. Нажмите на кнопку *Тест*, чтобы проверить соединение с Redis. Результат проверки ("Успешно" или "Ошибка") отобразится в диалоговом окне.
. Сохраните изменения настроек базы данных.
. Если настраивается кластер серверов {dv}, подключите все сервера к одному кэш-серверу Redis.
