= Протоколирование работы сервиса полнотекстового индексирования

События сервиса регистрируются в журнале работы. Расположение журнала, а также параметры журналирования настраиваются в конфигурационном файле `/usr/lib/docsvision/fulltextservice/appsettings.json` в секции `NLog`.

[source,json]
----
  "NLog": {
    "targets": {
      "file": {
        "type": "File",
        "fileName": "${gdc:baseLogFolder}/docsvision/fulltext/${shortdate}.log", <.>
        "layout": "${longdate}|${event-properties:item=EventId_Id}|${uppercase:${level}}|${logger}|${message} ${exception:format=tostring}"
      }
    },
    "rules": [
      {
        "logger": "*",
        "minLevel": "Warn",
        "writeTo": "file"
      }
    ]
  },
----
<.> Путь к файлу журнала указан в параметре `fileName`.

По умолчанию файлы журнала сохраняются в каталог `/var/log/docsvision`. Новый журнал создаётся после истечения заданного интервала времени. Каждый день журнал сохраняется в архив. Максимальное число сохраненных архивов 30.

Дополнительная информация по настройке журналирования приведена https://nlog-project.org[на сайте] компонента NLog.

[#indexing-status]
== Состояние полнотекстового индекса

Состояние индексов при запуске индексирования может изменяться. Ниже приведены более подробные расшифровки состояний:

* `Installed` -- созданы все необходимые объекты, но индексы пусты. В данном случае консоль только завершила процесс создания индексов.
* `Initializing` -- происходит индексирование карточек, созданных за прошедший период неактивности индексации.
* `InitPaused` -- процесс инициализации приостановлен. Вероятнее всего, процесс был остановлен из-за ошибки.
* `Active` -- все процессы индексации завершены.
* `Updating` -- обновление информации в карточках, которые были изменены за прошедший период.
* `UpdatingPaused` -- процесс обновления приостановлен. Вероятнее всего, процесс был остановлен из-за ошибки.

В случае наблюдения любых проблем в работе полнотекстового поиска, которые невозможно решить самостоятельно, следует xref:system::technical-support.adoc[обратиться в техническую поддержку {dv}], к обращению необходимо прикрепить лог сервера за время наблюдения проблем и лог полнотекстового поиска.
