= Особенности настройки кластера сервисов полнотекстового индексирования

Сервис полнотекстового индексирования может быть организован из нескольких экземпляров сервиса на нескольких компьютерах в кластере. Данная структура позволяет распределить нагрузку, связанную с получением данных для индексирования, между несколькими узлами.

.Чтобы организовать кластер сервисов полнотекстового индексирования:
. Настройте экземпляр сервиса полнотекстового индексирования, установленного с {dv}, стандартным образом, или установите и настройте сервис полнотекстового индексирования xref:search-separate-install.adoc[отдельно от сервера {dv}].
. Установите второй экземпляр сервиса полнотекстового индексирования xref:search-separate-install.adoc[отдельно] от основного сервера.
. Внесите изменения в реестр ОС на компьютере второго узла:
[lowerroman]
.. Создайте ветку `{hklm-dv}Platform\Server\Databases`.
.. Скопируйте в ветку параметры из аналогичной ветки реестра сервера {dv}, данные которого индексируются. Копируемые параметры содержат информацию о БД {dv}.
. Перезапустите службу *{fts}* на созданном узле кластера.
. Если требуется, создайте и настройте другие узлы кластера аналогичным образом.
