= Ограничить размер файлового кэша

Сервер {dv} кэширует файлы запрашиваемые клиентами в папку `C:\Windows\TEMP\Название-БД\FileCache`.

.Разрастание кэша ограничивается двумя параметрами:
* `FileCacheSize` -- устанавливает максимальный размер кэша от *общего размера диска*, на котором размещается кэш. Значение задаётся в процентах: от `0` до `100`. По умолчанию: `10%`.
* `FileCacheMaxFilesCount` -- устанавливает максимальное количество файлов в файловом кэше. По умолчанию: `1000 файлов`.

Очистка файлового кэша выполняется при запуске IIS и при чтении файла, если превышено значение `FileCacheSize` или `FileCacheMaxFilesCount`.

.Администратор может изменить установленные ограничения:
. Откройте реестр ОС на сервере {dv}.
. Перейдите в раздел `{hklm-dv}\Platform\5.5\Server`.
. Измените значение параметров `FileCacheSize` и/или `FileCacheMaxFilesCount`.
+
****
Если параметр(ы) отсутствует, создайте:

* Тип параметра: `DWORD`.
* Название: `FileCacheSize` или `FileCacheMaxFilesCount`.
* Значение:
** Для FileCacheSize -- от `0` до `100`.
** Для FileCacheMaxFilesCount -- от `0`.
****

[#rest-cache]
== Файловый кэш для менеджера объектов Rest

При попытке доступа к файлам менеджер объектов Rest кэширует информацию о них. Кэш не хранится на диске, а располагается в памяти. Кеш разделяется между всеми сессиями, включая сессии разных пользователей. Для существующих БД кэширование по умолчанию отключено. Кэширование регулируется настройками `MaxFileDataEntrySize` и `MaxFileDataCacheSize` в ветке реестра `HKEY_LOCAL_MACHINE\SOFTWARE\DocsVision\Platform\5.5\ObjectManager`. Необходимо самостоятельно создать ключи реестра с типом `dword` в указанной ветке.

* Максимальный размер кэшируемых файлов можно настроить при помощи параметра `MaxFileDataEntrySize`. По умолчанию указывается значение `65536` байт (64 Кб).
* Общий размер кэша в памяти задаёт настройка `MaxFileDataCacheSize`, по умолчанию значение составляет `67108864` байт (64 Мб).

При превышении размера кэша очищаются данные наименее часто используемых файлов согласно статистике обращений к файлу.
