= Ограничить размер файлового кэша

Сервер {dv} кэширует файлы запрашиваемые клиентами в папку `C:\Windows\TEMP\Название-БД\FileCache`.

.Разрастание кэша ограничивается двумя параметрами:
* `FileCacheSize` -- устанавливает максимальный размер кэша от *общего размера диска*, на котором размещается кэш. Значение задаётся в процентах: от `0` до `100`. По умолчанию: `10%`.
* `FileCacheMaxFilesCount` -- устанавливает максимальное количество файлов в файловом кэше. По умолчанию: `1000 файлов`.

Очистка файлового кэша выполняется при запуске IIS и при чтении файла, если превышено значение `FileCacheSize` или `FileCacheMaxFilesCount`.

.Администратор может изменить установленные ограничения:
. Откройте реестр ОС на сервере {dv}.
. Перейдите в раздел `{hklm-dv}\Platform\5.5\Server`.
. Измените значение параметров `FileCacheSize` и/или `FileCacheMaxFilesCount`.
+
****
Если параметр(ы) отсутствует, создайте:

* Тип параметра: `DWORD`.
* Название: `FileCacheSize` или `FileCacheMaxFilesCount`.
* Значение:
** Для FileCacheSize -- от `0` до `100`.
** Для FileCacheMaxFilesCount -- от `0`.
****

[#rest-cache]
== Файловый кэш для менеджера объектов Rest

При попытке доступа к файлам менеджер объектов Rest кэширует информацию о них. Кэш не хранится на диске, а располагается в памяти. Кэш разделяется между всеми сессиями, включая сессии разных пользователей. Для существующих БД кэширование по умолчанию включено. Отключение или настройка кэширования выполняется при помощи параметров реестра в ветке `HKEY_LOCAL_MACHINE\SOFTWARE\DocsVision\Platform\5.5\ObjectManager`:

* `DisabledCaching` -- параметр отключает кэширование. Значение по умолчанию: `0` -- включено, для отключения укажите `1`.
* `MaxFileDataEntrySize` -- регулирует максимальный размер кэшируемых файлов. Значение по умолчанию -- `65536` байт (64 Кб).
* `MaxFileDataCacheSize` -- задаёт общий размер кэша в памяти. Значение по умолчанию составляет `67108864` байт (64 Мб). При превышении размера кэша очищаются данные наименее часто используемых файлов согласно статистике обращений к файлу.

NOTE: Если параметры отсутствуют, создайте их самостоятельно в указанной ветке с типом `dword`.
