= Установка базовых модулей на Linux

Данный раздел описывает установку базовых модулей для ОС Linux. Все описанные ниже команды необходимо выполнять после завершения xref:install-platform.adoc[установки] модуля {pl}.

При установке модулей {dv} в ОС Linux разделение на серверную и клиентскую части отсутствует. Установка выполняется описанными ниже командами, другие базовые модули будут установлены автоматически.

[#webc]
== Установка {wc}а

. Установите пакеты модуля:
+
[source,bash]
----
sudo apt-get install docsvision-webclient
----
+
. Отредактируйте файл настроек модуля:
+
[source,bash]
----
sudo nano /usr/lib/docsvision/webclient/appsettings.json
----
+
. Запустите службу {wc}а:
+
[source,bash]
----
sudo systemctl start dvwebclient
----
+
. Теперь вы можете запустить {wc}, перейдя по адресу: `\http://WebC-server.domain.com/Account/Login`.

[#sett-serv]
== Установка Сервиса настроек

. Установите сервис:
+
[source,bash]
----
sudo apt-get install docsvision-settingsservice
----
+
. Отредактируйте файл настроек:
+
[source,bash]
----
sudo nano /usr/lib/docsvision/SettingsService/appsettings.json
----
+
. Запустите сервис:
+
[source,bash]
----
sudo systemctl start dvsettings
----

[#ext-api]
== Установка Сервиса внешнего API {of-mc}

. Установите сервис внешнего API:
+
[source,bash]
----
sudo apt-get install docsvision-externalapi
----
+
. Отредактируйте файл настроек:
+
[source,bash]
----
sudo nano /usr/lib/docsvision/externalapi/appsettings.json
----
+
. Запустите сервис внешнего API {of-mc}:
+
[source,bash]
----
sudo systemctl start dvexternalapi
----

include::upgrade:551-552:post-update.adoc[tags=console]

. Следующей командой установите {mc}:
+
[source,bash]
----
sudo apt-get install docsvision-managementconsole
----
+
. Отредактируйте файл настроек модуля:
+
[source,bash]
----
sudo nano /usr/lib/docsvision/managementconsole/appsettings.json
----
+
. Запустите службу:
+
[source,bash]
----
sudo systemctl start dvconsole
----
+
. Теперь вы можете открыть Консоль управления из браузера по адресу `\http://console.domain.com:5100`
+
NOTE: При авторизации укажите имя в формате `user@domain.com`, вариант `domain\user` не работает.

[#worker]
== Установка Службы {ws}

. Установите модуль Служба {ws} следующей командой:
+
[source,bash]
----
sudo apt-get install docsvision-workerservice
----
+
. Отредактируйте конфигурационный файл:
+
[source,bash]
----
sudo nano /usr/lib/docsvision/workerservice/Configuration.json
----
+
. Запустите службу модуля:
+
[source,bash]
----
sudo systemctl start dvworkerservice
----

[#purge]
== Удаление ненужных пакетов

. Удалите ненужные системе пакеты (зависимости, которые принесли за собой другие пакеты при установке) командой:
+
[source,bash]
----
sudo apt-get autoremove
----

Ознакомьтесь со списком полезных команд в пункте xref:admin:post-config-server.adoc[]
