= Настроить размер пула соединений с сервером БД

Сервер приложений {dv} при работе с сервером БД использует пул соединений фиксированного размера. Изменить размер пула по умолчанию можно с помощью специальной настройки в реестре. По умолчанию данная настройка отсутствует, а размер задан как `100 соединений`.

Чтобы изменить количество соединений, необходимо в ветке `{hklm}\SOFTWARE\DocsVision\Platform\5.5\Server` создать параметр `DbConnectionPoolSize (dword)`, в котором определить требуемый размер пула.

[WARNING]
====
Увеличение размера пула может привести к увеличению потребляемой памяти на серверах приложений и баз данных.
====

Конфигурировать СУБД нужно учитывая перечисленные ниже факты:

Используя настройки *max_connections* в БД {pgsql} можно ограничить количество подключений к серверу БД. Настройка влияет на подключения к серверу БД, а не к БД. Если на сервере {pgsql} несколько БД, ограничение влияет на общее количество подключений к серверу: может быть открыто 60 соединений с одной БД, а с другой удастся открыть лишь 40, дальнейшие попытки открыть подключение выдадут ошибку.

Настройка *DbConnectionPoolSize* определяет максимальный размер пула соединений с базой на клиентской стороне, а не с сервером. Tсли на одном сервере приложений подключили две БД {pgsql} c одного инстанса, то *{sss}* при определённых нагрузках может пытаться открыть по 100 соединений к каждой БД, то есть 200 подключений к одному инстансу {pgsql}.

Если два сервера приложений обрабатывают одну БД {pgsql}, то каждый *{sss}* может пытаться открыть по 100 соединений к этой базе, то есть 200 подключений к одному инстансу {pgsql}.

Также нужно помнить о подключениях от _pgagent_, каких-то дополнительных соединениях от _pgadmin_ (или другой среды администрирования), ServerConsole, сервиса полнотекстового индексирования, файлового сервиса.
