// tag::atomic[]
****
Параметр _Ожидать завершения атомарной операции на SQL Server (сек)_ определяет максимальное время ожидания завершения отдельного этапа (операции) процедуры создания или подключения БД. Если операция не будет выполнена за указанное время, она завершится с ошибкой.

[NOTE]
====
Параметр _Ожидать завершения атомарной операции на SQL Server (сек)_ не ограничивает время выполнения пользовательских операций при работе в {wincl}е или {wc}е. при работе в клиентских приложениях будет применяться стандартное ограничение `600 секунд`.
====
****
// end::atomic[]

// tag::satellite[]
Не рекомендуется включать или отключать сателлитные БД, если подключается БД {dv} версии 5.5. В противном случае часть данных станет недоступна. Данные из основной БД в сателлитную и обратно не переносятся.
// end::satellite[]

// tag::storageLimits[]
* Для СУБД Microsoft SQL Server существует ограничение на размер добавляемых файлов -- не более 2 Гб. Если в {dv} необходимо хранить файлы больше 2 Гб, используйте *_Хранилище на диске_*, *_Filestream хранилище в базе данных {dv}_*, *_FileStream хранилище во внешней базе данных MS SQL Server_* или другое хранилище, поддерживающее файлы такого размера.
+
Для СУБД PostgreSQL аналогичное ограничение составляет 1 Гб.
// end::storageLimits[]

// tag::connectionLine[]
`Data Source=ServerName;Initial Catalog=DatabaseName;User ID=UserName;Password=UserPassword`.
+
Строка должна содержать данные для подключения к внешней БД (по отношению к БД {dv}). В указанную внешнюю БД будут сохраняться бинарные данные файлов.
+
WARNING: Не указывайте текущую или любую другую БД {dv} -- это может привести к поломке БД.
// end::connectionLine[]
