= Размещение БД {dv} в группе доступности Microsoft SQL Server AlwaysOn

AlwaysOn -- предоставляемое Microsoft SQL Server решение для создания групп доступности с целью обеспечения высокой доступности и аварийного восстановления.

[NOTE]
====
Дополнительная информация по группам доступности AlwaysOn приведена на странице https://docs.microsoft.com/ru-ru/sql/database-engine/availability-groups/windows/overview-of-always-on-availability-groups-sql-server
====

В системе {dv} группа доступности AlwaysOn используется для снижения нагрузки на сервера баз данных, за счет переадресации некоторых операций чтения к репликам. {dv} самостоятельно выбирает наиболее "свежую" реплику для работы, а если такой нет -- получает данные с мастера.

[IMPORTANT]
====
Для использования функции AlwaysOn в {dv} требуется лицензия (опция "{dv} Кластер AlwaysOn"). Использования функции без лицензии приведёт к ошибке.
====

Реплики используются в операциях получения данных карточек, выполнения отчета с признаком "Только чтение", выполнения поисковых запросов и получения представлений.

Для использования данных возможностей нужно:

. Настроить AlwaysOn в Microsoft SQL Server.
. Включить поддержку AlwaysOn в системе {dv}.

Настройка группы доступности выполняется после создания БД {dv} (её нужно будет выбрать при настройке).

* xref:EnableAlwaysOnInSQLServer.adoc[Настройка группы доступности AlwaysOn].* xref:EnableAlwaysOnIn{dv}.adoc[Включение поддержки AlwaysOn в {dv}].
