[[ariaid-title1]]
== Приложение A. Группы безопасности Docsvision

В процессе установки и настройки серверной части Модуля будут созданы группы безопасности пользователей (если группы уже существуют на момент установки, их состав не изменяется):

Основные группы безопасности::
  DocsVision Users;;
    Члены группы имеют права на работу с системой Docsvision.
    +
    По умолчанию в группу включаются все пользователи, входящие в группу безопасности [.dfn .term]_Все_ ([.dfn .term]_Everyone_). Пользователи этой группы по умолчанию имеют уровень допуска `самый низкий`; при необходимости их уровень допуска может быть переопределен в [.dfn .term]_Справочнике сотрудников_.
  DocsVision Power Users;;
    Члены группы имеют права просмотра всех объектов системы [.dfn .term]_Docsvision_, включая чтение системного журнала, исключая, возможность изменения прав доступа.
    +
    По умолчанию пользователи в эту группу не включаются.
  DocsVision Administrators;;
    Члены группы – администраторы Docsvision, имеют право доступа к базе, ряду административных функций, а также возможность чтения и предоставления прав доступа (но не изменения назначенного уровня безопасности) ко всем объектам базы данных.
    +
    Пользователь, входящий в эту группу может архивировать и разархивировать карточки, на которые у него есть права, находить в архиве любые карточки, отображать содержимое архива в представлении Windows-клиент и [.dfn .term]_РМА Docsvision_;
    +
    Пользователи этой группы всегда имеют уровень допуска `высокий`, несмотря на то, какой уровень указан для конкретного пользователя в [.dfn .term]_Справочнике сотрудников_.
    +
    В группу автоматически включается пользователь, настроивший систему Docsvision.
  Docsvision Security Administrators;;
    Члены группы обладают всеми правами [.keyword .parmname]_DocsVision Administrators_, а кроме того могут изменять уровни безопасности, назначенные субъектам и объектам системы.
    +
    Пользователь, входящий в эту группу может архивировать, разархивировать и находить в архиве любые карточки.
    +
    Пользователи этой группы всегда имеют уровень допуска `самый высокий`, несмотря на то, какой уровень указан для конкретного пользователя в [.dfn .term]_Справочнике сотрудников_.
    +
    В группу автоматически включается пользователь, настроивший систему Docsvision.
  DocsVision Archive Operators;;
    Члены группы имеют право архивировать и разархивировать и находить в архиве только те карточки [.dfn .term]_Docsvision_, на работу с которыми у него есть права (минимальные требования — права на чтение и изменение).
    +
    Группа создается на сервере [.dfn .term]_Docsvision_ и используется для проверки прав при работе с архивом. По умолчанию пользователи в эту группу не включаются.
    +
    Участникам группы предоставляются права группы [.keyword .parmname]_DocsVision Users_.
Дополнительные группы безопасности::
  DocsVision Workflow Process Creators;;
    Члены группы имеют право создавать и редактировать шаблоны и экземпляры БП модуля «Управление процессами». Поскольку БП во время исполнения имеет доступ к защищенным объектам, состав этой группы не менее важен, чем состав группы [.keyword .parmname]_DocsVision Administrators_.
    +
    Участникам группы предоставляются права группы [.keyword .parmname]_DocsVision Users_.
    +
    В группу автоматически включается пользователь, настроивший систему Docsvision.
  DocsVision Search Query Creators;;
    Члены группы имеют право работать с окном расширенного поиска (вызывать окно поиска из приложения Windows-клиент, создавать и сохранять поисковые запросы), создавать и редактировать личные и общие запросы, удалять и импортировать общие запросы [.dfn .term]_Личного помощника_.
    +
    По умолчанию в эту группу включаются все пользователи, входящие в группу безопасности [.dfn .term]_Все_ ([.dfn .term]_Everyone_).
    +
    Пользователям, включенным в группу [.keyword .parmname]_Docsvision Search Query Creators_, должны быть предоставлены права на чтение и изменение системной папки [.keyword]*Результаты поиска*.
    +
    Участникам группы предоставляются права группы [.keyword .parmname]_DocsVision Users_.

*На уровень выше:* xref:../topics/Appendixes.adoc[Приложения]
