= Приложение A. Группы безопасности {dv}

В процессе установки и настройки серверной части модуля будут созданы группы безопасности пользователей (если группы уже существуют на момент установки, их состав не изменяется):

Основные группы безопасности::
  DocsVision Users;;
    Члены группы имеют права на работу с системой {dv}.
    +
    По умолчанию в группу включаются все пользователи, входящие в группу безопасности _Все_ (_Everyone_). Пользователи этой группы по умолчанию имеют уровень допуска `самый низкий`; при необходимости их уровень допуска может быть переопределен в _Справочнике сотрудников_.
  DocsVision Power Users;;
    Члены группы имеют права просмотра всех объектов системы _{dv}_, включая чтение системного журнала, исключая, возможность изменения прав доступа.
    +
    По умолчанию пользователи в эту группу не включаются.
  DocsVision Administrators;;
    Члены группы – администраторы {dv}, имеют право доступа к базе, ряду административных функций, а также возможность чтения и предоставления прав доступа (но не изменения назначенного уровня безопасности) ко всем объектам базы данных.
    +
    Пользователь, входящий в эту группу может архивировать и разархивировать карточки, на которые у него есть права, находить в архиве любые карточки, отображать содержимое архива в представлении Windows-клиент и _РМА {dv}_;
    +
    Пользователи этой группы всегда имеют уровень допуска `высокий`, несмотря на то, какой уровень указан для конкретного пользователя в _Справочнике сотрудников_.
    +
    В группу автоматически включается пользователь, настроивший систему {dv}.
  {dv} Security Administrators;;
    Члены группы обладают всеми правами [.keyword .parmname]_DocsVision Administrators_, а кроме того могут изменять уровни безопасности, назначенные субъектам и объектам системы.
    +
    Пользователь, входящий в эту группу может архивировать, разархивировать и находить в архиве любые карточки.
    +
    Пользователи этой группы всегда имеют уровень допуска `самый высокий`, несмотря на то, какой уровень указан для конкретного пользователя в _Справочнике сотрудников_.
    +
    В группу автоматически включается пользователь, настроивший систему {dv}.
  DocsVision Archive Operators;;
    Члены группы имеют право архивировать и разархивировать и находить в архиве только те карточки _{dv}_, на работу с которыми у него есть права (минимальные требования — права на чтение и изменение).
    +
    Группа создается на сервере _{dv}_ и используется для проверки прав при работе с архивом. По умолчанию пользователи в эту группу не включаются.
    +
    Участникам группы предоставляются права группы [.keyword .parmname]_DocsVision Users_.
Дополнительные группы безопасности::
  DocsVision Workflow Process Creators;;
    Члены группы имеют право создавать и редактировать шаблоны и экземпляры БП модуля "Управление процессами". Поскольку БП во время исполнения имеет доступ к защищенным объектам, состав этой группы не менее важен, чем состав группы [.keyword .parmname]_DocsVision Administrators_.
    +
    Участникам группы предоставляются права группы [.keyword .parmname]_DocsVision Users_.
    +
    В группу автоматически включается пользователь, настроивший систему {dv}.
  DocsVision Search Query Creators;;
    Члены группы имеют право работать с окном расширенного поиска (вызывать окно поиска из приложения Windows-клиент, создавать и сохранять поисковые запросы), создавать и редактировать личные и общие запросы, удалять и импортировать общие запросы _Личного помощника_.
    +
    По умолчанию в эту группу включаются все пользователи, входящие в группу безопасности _Все_ (_Everyone_).
    +
    Пользователям, включенным в группу [.keyword .parmname]_{dv} Search Query Creators_, должны быть предоставлены права на чтение и изменение системной папки *Результаты поиска*.
    +
    Участникам группы предоставляются права группы [.keyword .parmname]_DocsVision Users_.

