= Особенности хранения архивных данных в {dv}

Архив {dv} предназначен для хранения неиспользуемых в оперативной деятельности данных, которые при этом представляют интерес для организации.

В зависимости от настроек, архивные данные могут храниться в основной БД {dv} (таблицы с архивными данными имеют постфикс *\_archive*) или в отдельной _архивной базе данных_.

Архивная база данных -- xref:db-satellite.adoc[сателлитная база данных] {dv}, которая предназначена для хранения данных архивных карточек. Архивная база данных имеет название: *Название-основной-БД-{dv}_Archive*.

Использование отдельной БД для хранения архивных карточек позволяет снизить нагрузку на основную БД, облегчить её обслуживание и сократить время на создание её резервных копий.

Чтобы использовать архивную БД, лицензия {dv} должна содержать опцию _{dv} Архивная база данных_.

Способ хранения архивных данных определяется при создании БД {dv}, и не может быть изменен без последствий после создания. См. подробнее о сателлитных БД в пункте xref:db-satellite.adoc[].

Карточка перемещается в архив, если к ней добавлен атрибут _Архивирована_ (см. подробнее в документе Руководство пользователя модуля _{wincl}_, пункт _Архивирование данных_). Карточка будет извлечена из архива, если атрибут удалён. Карточки, находящиеся в архиве, доступны только для чтения.

Помещать карточки в архив, извлекать карточки из архива, открывать архивированные карточки и находить их с помощью поисковых запросов могут только пользователи из следующих групп:

* *{dv-arch-ops-serv}*.
* *{dv-admins-serv}*.
* *{dv-sec-admins-serv}*.

Для всех остальных пользователей карточки в архиве недоступны и не отображаются в клиентских программах. Правом на удаление архивных карточек обладают только пользователи, включённые в группу _{dv} Archive Operators_ (Операторы архива).
