[[ariaid-title1]]
== Назначение персональной лицензии

Количество пользовательских подключений к серверу Docsvision ограничено (лицензией). После исчерпания пула конкурентных лицензий (за которые конкурируют пользователи), новые пользователи не смогут войти в Docsvision.

Чтобы предоставить определенному пользователю возможность подключаться к Docsvision независимо от наличия свободных конкурентных лицензий, нужно назначить ему персональную лицензию.

[NOTE]
====
[.note__title]#Important:# Для назначения персональной лицензии в лицензии Docsvision должна быть дополнительная опция «Docsvision Personal (VIP) Licenses». Общее число пользователей, которым может быть назначена персональная лицензия, указано в примечании к опции «Docsvision Personal (VIP) Licenses».
====

Чтобы назначить персональную лицензию:

. [.ph .cmd]#Откройте раздел [.keyword .wintitle]*Управление лицензиями* Консоли настройки.#
. [.ph .cmd]#Нажмите на кнопку [.ph .uicontrol]*Добавить*.#
. [.ph .cmd]#Выберите учетную запись пользователя, которому назначается лицензия.#
+
В список [.ph .uicontrol]*Персональные лицензии* будет добавлена выбранная учетная запись; персональная лицензия будет назначена.

Чтобы освободить назначенную персональную лицензию:

[start=4]
. [.ph .cmd]#Выберите учетную запись, персональная лицензия которой освобождается, в списке [.ph .uicontrol]*Персональные лицензии*.#
. [.ph .cmd]#Нажмите на кнопку [.ph .uicontrol]*Удалить*.#
+
Учетная запись будет удалена из списка; персональная лицензия будет освобождена.

После изменения списка персональных лицензий нужно перезапустить сервер Docsvision (IIS и службу «Docsvision 5.5 StorageServer»), а также клиентские приложения (РМА, Windows-клиент, Web-клиент).

[NOTE]
====
[.note__title]#Important:# Если пользователь, имеющий персональную лицензию, работает под своей учетной записью на двух или более компьютерах, то при втором и последующих соединениях он получит их из пула конкурентных лицензий.
====

*Parent topic:* xref:../topics/LicensesMore.adoc[Управление лицензиями]
