= Назначение персональной лицензии

Количество пользовательских подключений к серверу {dv} ограничено (лицензией). После исчерпания пула конкурентных лицензий (за которые конкурируют пользователи), новые пользователи не смогут войти в {dv}.

Чтобы предоставить определенному пользователю возможность подключаться к {dv} независимо от наличия свободных конкурентных лицензий, нужно назначить ему персональную лицензию.

[NOTE]
====
[.note__title]#Important:# Для назначения персональной лицензии в лицензии {dv} должна быть дополнительная опция "{dv} Personal (VIP) Licenses". Общее число пользователей, которым может быть назначена персональная лицензия, указано в примечании к опции "{dv} Personal (VIP) Licenses".
====

Чтобы назначить персональную лицензию:

. Откройте раздел *Управление лицензиями* Консоли настройки.
. Нажмите на кнопку *Добавить*.
. Выберите учетную запись пользователя, которому назначается лицензия.
+
В список *Персональные лицензии* будет добавлена выбранная учетная запись; персональная лицензия будет назначена.

Чтобы освободить назначенную персональную лицензию:

[start=4]
. Выберите учетную запись, персональная лицензия которой освобождается, в списке *Персональные лицензии*.
. Нажмите на кнопку *Удалить*.
+
Учетная запись будет удалена из списка; персональная лицензия будет освобождена.

После изменения списка персональных лицензий нужно перезапустить сервер {dv} (IIS и службу "{dv} 5.5 StorageServer"), а также клиентские приложения (РМА, {wincl}, Web-клиент).

[NOTE]
====
[.note__title]#Important:# Если пользователь, имеющий персональную лицензию, работает под своей учетной записью на двух или более компьютерах, то при втором и последующих соединениях он получит их из пула конкурентных лицензий.
====

