= Изменение режима формирования представлений в базе данных

Представления, с помощью которых в {dv} отображается содержимое папок, представляют собой специальным образом сформированные таблицы в базе данных {dv}. Часть данных для работы представлений формируется заданием "ObjectValidation" базы данных, на время выполнения которого напрямую влияет количество пользователей и представлений в системе {dv}.

Администратор может изменить режим формирования представлений: формировать представления предварительно заданием "ObjectValidation" или формировать представления при обращении пользователей. Во втором случае на первое открытие представлений потребуется больше времени.

Для изменения режима формирования представлений выполните в базе данных следующий скрипт:

* для формирования представлений заданием "ObjectValidation":
+
[source]
----
decalre @value bit = 1
exec dvsys_setting_set 'CreateViewKeysetTablesInsideObjectValidation', @value
----
* для формирования представлений при обращении:
+
[source]
----
decalre @value bit = 0
exec dvsys_setting_set 'CreateViewKeysetTablesInsideObjectValidation', @value
----

