= Конфигурация модуля {pl}

Все настройки модуля хранятся в конфигурационном файле модуля `appsettings.json`. Конфигурационный файл может быть изменён в любом текстовом редакторе, например `nano`.

[source,bash]
----
sudo nano /usr/lib/docsvision/platform/appsettings.json
----

.appsettings.json
[source,json]
----
{
  "DocsVision": {
    "Platform": {
      "Server": {
        "DefaultBaseName": "alias", <.>
        "LogFile": "/var/log/docsvision/dvappserver.log", <.>
        "WindowsSecurityServerName": "any.domain.com", <.>
        "Databases": {
          "alias": "CONNECTION-STRING"  <.>
        }
      }
    }
  },
  "Groups": {
    "DocsVision Administrators": [
      "domain\\account"
    ], <.>
    "DocsVision Security Administrators": [
      "domain\\account"
    ]
  },
  "Ldap": {
    "AuthType": "Basic",
    "Credential": {
      "UserName": "account@domain.com",
      "Password": "password"
    }
  },
  "Domains": [
    "DOMAIN.COM"
  ],
  "DataProtectCertificateThumbprint": "thumbprint", <.>
  "SystemUserAccount": "account@domain.com",
  "SystemUserPassword": "password", <.>
  "Logging": { <.>
    "LogLevel": {
      "Default": "Error"
    }
  },
  "APIKEY": "anything" <.>
}
----
<.> Псевдоним базы данных. Должен совпадать с псевдонимом подключаемой базы в Консоли настройки. Можно заполнить заранее, или вернуться позже, после создания из Консоли управления.
<.> Путь к файлу журнала сервера.
<.> Необходимо указать имя любого компьютера в текущем домене Active Directory. Используется при получении списка доступных членов домена при настройке дискреционной безопасности в {wincl}е, РМА и DVExplorer.
<.> Строка подключения базы данных, подробнее см. <<connection-string,ниже>>.
+
<.> Эквивалент системных групп. Указанные в группах пользователи будут обладать соответствующими правами. Обратите внимание, что в группах массив строк, а не строка.
<.> Отпечаток закрытого ключа шифрования. Отпечаток закрытого ключа шифрования SHA1. Указывается без двоеточия `D8602179888DC8402B393F11DCA16A3376DDF879`, см. подробнее в документации по установке системы, раздел "xref:6.1@install-linux::account-protection.adoc[]".
<.> Пароль рекомендуется хранить в зашифрованном виде, см. подробнее в документации по установке системы, раздел "xref:6.1@install-linux::account-protection.adoc[]".
<.> Настройка уровня журналирования.
<.> Используется для аутентификации в API {wf}. При запуске бизнес-процесса из клиента через серверное расширение вызывается API сервера {wf}, который запускает данный БП.

После установки на сервере необходимо настроить группы безопасности.

Группы безопасности настраиваются в секции `"Groups"` конфигурационного файла `appsettings.json`.

.Пользователь, выполняющий установку и настройку системы должен входить в следующие группы:
* *{dv-admins-serv}* и *{dv-sec-admins-serv}* -- администраторы системы и администраторы безопасности системы.
* *{dv-web-admin-cns-admins-serv}*. Пользователи, входящие в эту группу, имеют право работать с xref:6.1@mgmtconsole:admin:install.adoc[Консолью управления {dv}].

[#connection-string]
== Строка подключения к БД

.{mssql}
****
`Initial Catalog=Имя-БД-с-FileStream; Data Source=Полное-имя-сервера-СУБД; User ID=Имя-пользователя; Password=Пароль-пользователя;`
****

{pgsql}
****
`Server=Адрес-сервера-базы-данных; Port=SQL-порт; Database=Название-БД; User ID=Имя-пользователя; Password=Пароль-пользователя;`
****
