= Настройка СУБД Microsoft SQL Server

Сервер Microsoft SQL Server, на котором будет размещаться база данных {dv}, должен быть настроен специальным образом.

. Переключите режим аутентификации (Authentication) СУБД в положение [.keyword .parmname]_SQL Server and Windows_ или [.keyword .parmname]_Windows_.
. Отключите опцию "Case sensitive collation".
. Убедитесь, что на компьютере с СУБД и на компьютере, на который устанавливается серверная часть модуля, синхронизированы время и часовой пояс.
. В настройках Microsoft SQL Server установите параметры [.keyword .parmname]_remote access_ и [.keyword .parmname]_remote admin connections_ в значение "1".
+
[NOTE]
====
[.note__title]#Прим.:# Проверить текущие настройки можно, выполнив процедуру *sp_configure*.
====
. Включите параметр конфигурации сервера [.keyword .parmname]_xp_cmdshell_ (см. http://msdn.microsoft.com/ru-ru/library/ms190693.aspx[Параметр xp_cmdshell]), позволяющий системным администраторам контролировать, должна ли расширенная системная процедура [.keyword .parmname]_xp_cmdshell_ выполняться в системе (исполнение этой процедуры автоматически разрешается в {dv}, только если явно задан каталог для хранения записей журнала).
+
Если данный параметр отключен, то процедура очистки журнала проводиться не будет.
. Убедитесь, что на сервере с Microsoft SQL Server открыт порт *1433* для подключения к СУБД.

