= Конфигурация модуля {pl}

Все настройки модуля хранятся в конфигурационном файле модуля `appsettings.json`. Конфигурационный файл может быть изменён в любом текстовом редакторе, например `nano`.

[source,bash]
----
sudo nano /usr/lib/docsvision/platform/appsettings.json
----

.Фрагмент конфигурационного файла `appsettings.json`:
[source,json]
----
{
  "DocsVision": {
    "Platform": {
      "Server": {
        "DefaultBaseName": "alias", <.>
        "LogFile": "/var/log/docsvision/dvappserver.log", <.>
        "WindowsSecurityServerName": "any.domain.com", <.>
        "Databases": {
          "alias": "CONNECTION-STRING"  <.>
        }
      }
    }
  },
  "Groups": {
    "DocsVision Administrators": [
      "domain\\account"
    ], <.>
    "DocsVision Security Administrators": [
      "domain\\account"
    ]
  },
  "Ldap": { <.>
    "AuthType": "Basic", <.>
    "Credential": {
      "UserName": "account@domain.com", <.>
      "Password": "password" <.>
    }
  },
  "Domains": [
    "DOMAIN.COM" <.>
  ],
  "DataProtectCertificateThumbprint": "thumbprint", <.>
  "SystemUserAccount": "account@domain.com", <.>
  "SystemUserPassword": "password", <.>
  "Logging": { <.>
    "LogLevel": {
      "Default": "Error"
    }
  },
  "ApiKey": "api-key" <.>
}
----
<.> `DefaultBaseName` -- псевдоним базы данных. Должен совпадать с псевдонимом подключаемой базы в Консоли настройки. Можно заполнить заранее, или вернуться позже, после создания из Консоли управления.
<.> `LogFile` -- путь к файлу журнала сервера.
<.> `WindowsSecurityServerName` -- необходимо указать имя любого компьютера в текущем домене Active Directory. Используется при получении списка доступных членов домена при настройке дискреционной безопасности в {wincl}е, РМА и DVExplorer.
<.> `alias` -- псевдоним используемой БД, для которой задаётся строка подключения. `CONNECTION-STRING` -- строка подключения, подробное описание строки подключения см. <<connection-string,ниже>>.
+
<.> `Groups` -- эквивалент системных групп. Указанные в группах пользователи будут обладать соответствующими правами. Обратите внимание, что в группах массив строк, а не строка.
<.> `Ldap` -- имя и пароль учётной записи, под которой процесс обращается к ActiveDirectory.
<.> `AuthType` -- тип аутентификации: `Basic` -- аутентификация через LDAP, `Oauth` -- аутентификация через ЕСИА или Azure.
<.> `UserName` -- логин пользователя модуля для аутентификации LDAP.
<.> `Password` -- пароль учётной записи пользователя для аутентификации LDAP в открытом или в зашифрованном виде, см. подробнее о шифровании в документации по установке системы, раздел "xref:6.1@install-linux::account-protection.adoc[]".
<.> `Domains` -- домен сервера {dv}.
<.> `DataProtectCertificateThumbprint` -- Отпечаток закрытого ключа шифрования SHA1. +
Указывается без двоеточия, например, `D8602179888DC8402B393F11DCA16A3376DDF879`, см. подробнее в документации по установке системы, раздел "xref:6.1@install-linux::account-protection.adoc[]". +
Если шифровать пароль системной учётной записи не планируется, параметр можно удалить.
<.> `SystemUserAccount` -- имя системной учётной записи {dv}.
<.> `SystemUserPassword` -- пароль системной УЗ рекомендуется хранить в зашифрованном виде, см. подробнее в документации по установке системы, раздел "xref:6.1@install-linux::account-protection.adoc[]".
<.> `Logging` -- настройка уровня журналирования.
<.> `ApiKey` -- используется для подключения серверного расширения {wf}. Можно оставить значение по умолчанию или изменить, главное условие, чтобы значения в конфигурации модулей {wc}, {pl} и {wf} были одинаковые.

После установки на сервере необходимо настроить группы безопасности.

Группы безопасности настраиваются в секции `"Groups"` конфигурационного файла `appsettings.json`.

.Пользователь, выполняющий установку и настройку системы должен входить в следующие группы:
* *{dv-admins-serv}* и *{dv-sec-admins-serv}* -- администраторы системы и администраторы безопасности системы.
// * *{dv-web-admin-cns-admins-serv}*. Пользователи, входящие в эту группу, имеют право работать с xref:6.1@mgmtconsole:admin:install-server.adoc[Консолью управления {dv}].

[#connection-string]
== Строка подключения к БД

.{mssql}
****
`Initial Catalog=Имя-БД-{dv}; Data Source=Полное-имя-сервера-СУБД; User ID=Имя-пользователя; Password=Пароль-пользователя;`
****

{pgsql}
****
`Server=Адрес-сервера-базы-данных; Port=SQL-порт; Database=Название-БД; User ID=Имя-пользователя; Password=Пароль-пользователя;`
****
