= Установка службы PgAgent

Службу PgAgent предпочтительно устанавливать на сервер с СУБД PostgreSQL, но также, согласно официальной документации (https://www.pgadmin.org/docs/pgadmin4/4.x/pgagent_install.html), она может быть установлено отдельно.

Официальная инструкция по установке приведена на странице https://www.pgadmin.org/docs/pgadmin4/dev/pgagent.html.

Служба PgAgent может быть установлена на ОС Linux, Windows и macOS. Инструкция по загрузке пакетов установки PgAgent приведена на странице https://www.pgadmin.org/download/.

Далее установите PgAgent на компьютер с ОС Windows согласно https://www.pgadmin.org/docs/pgadmin4/latest/pgagent_install.html[инструкции]. Установка выполняется после завершения установки PostgreSQL. Затем выполните следующие шаги:

[[Configuring_PgAgent__section_vrl_ydp_thb]]
. Откройте файл `C:\Users\<Пользователь, под которым запущена служба "PostgreSQL Scheduling Agent - pgAgent>\AppData\Roaming\postgresql\pgpass.conf`.
. Добавьте в файл `pgpass.conf` строку:
+
[source,pre,codeblock]
----
<адрес сервера PG>:<порт>:<имя базы>:<имя пользователя>:<пароль пользователя>
----
+
В строке нужно указать свои значения для адреса сервера PostgreSQL, порта подключения, имени БД (можно заменить на "*" – все БД), имени и пароля пользователя, под которым выполняется подключение к серверу PostgreSQL.
. Запустите/перезапустите службу "PostgreSQL Scheduling Agent - pgAgent".

