[[ariaid-title1]]
== Настройка PostgreSQL для использования аутентификации Windows

. Создайте в PostgreSQL пользователей:
[loweralpha]
.. Для работы сервисов Docsvision: сервера Docsvision, сервиса полнотекстового поиска и файлового сервиса. Может использоваться одна учетная запись. Данным пользователям нужно предоставить права в соответствии с требованиями, приведёнными в xref:Appendix_B.adoc[Приложение B. Требования сервисов Docsvision].
.. Пользователя, от имени которого будет выполняться инициализация БД при первоначальной настройке Docsvision и последующее управления. Данному пользователю нужно предоставить права SUPERUSER.
.. Пользователя, от имени которого будет работать pgAgent.
+
Если имя доменной учетной записи пользователя или сервисной учетной записи содержит буквы верхнего регистра (например, «company\Sidorov.G»), в PostgreSQL необходимо добавить двух пользователей:
[loweralpha]
.. С сохранением оригинального регистра в имени, а именно: Sidorov.G.
.. С использованием букв только нижнего регистра, а именно: sidorov.g.
. В файл [.ph .filepath]`pg_hba.conf` добавьте строки:
+
[source,pre,codeblock]
----
host all all all sspi map=mymap
host all all all md5
----
. В файл [.ph .filepath]`pg_ident.conf` добавьте строки сопоставления пользователей Windows с пользователями СУБД, созданными на шаге 1:
+
[source,pre,codeblock]
----
mymap service@COMPANY service
mymap petrov.b@COMPANY petrov.b
mymap postgres@COMPANY postgres
----
+
Здесь service@COMPANY – имя пользователя в домене и название домена; service – имя пользователя в СУБД PostgreSQL.
. Запустите сервис PostgreSQL под доменной учетной записью (домена, в котором зарегистрированы пользователи из шага 3).
. В настройках службы «PostgreSQL Scheduling Agent - pgAgent» изменить пользователя на доменного пользователя из шага 3 (в данном примере: postgres@COMPANY).
. Измените строку запуска службы «PostgreSQL Scheduling Agent - pgAgent» в ветке `HKLM\SYSTEM\CurrentControlSet\Services\pgAgent` реестре. В значении user нужно указать пользователя PostgreSQL, указанного на шаге 3. Например:
+
[source,pre,codeblock]
----
C:\PROGRA~2\pgAgent\bin\pgagent.exe RUN pgAgent host=localhost port=5432 user=postgres dbname=postgres
----

[NOTE]
====
[.note__title]#Note:# Для получения более детальной информации по использованию аутентификации Windows в PostgreSQL обратитесь к документации PostgreSQL или другим ресурсам.
====

*Parent topic:* xref:../topics/Configuring_Software_for_PostgreSQL.adoc[Настройка СУБД PostgreSQL]
