= Настройка работы с несколькими доменами

{dv} поддерживает работу в одном или нескольких доменах. Для этого в конфигурационном файле модулей {pl} и {wc} поддерживается новая расширенная настройка доменных каталогов -- параметр `"Catalogs"`:

NOTE: Возможность настройки со старыми параметрами настройки через параметр `"Domains"` (для модуля {pl}) и параметр `"DefaultDomain"` (для модуля {wc}) сохраняется.

В конфигурационных файлах настройка представлена следующим массивом: `"Catalogs": []`. Если в массиве есть хоть одно описание каталога, включается новая логика работы -- будут учитываться только настройки из `"Catalogs": []`.

.Пример заполнения:
[source,json]
----
"Catalogs": [
  {
    "FullDomainName": "example1.com", <.>
    "NetBiosDomainName": "example1", <.>
    "LdapOptions": { <.>
      "LdapServerAddresses": [ "example1.com" ], <.>
      "AuthType": "Basic", <.>
      "Credential": { <.>
        "UserName": "user@example1.com",
        "Password": "Password"
      }
    }
  },
  {
    "FullDomainName": "example2.com", <.>
    "ChallengeTo": "example1.com" <.>
  }
]
----
<.> `FullDomainName` -- полное имя домена указывается в формате `user@example.com` учётной записи после `@`.
<.> `NetBiosDomainName` -- `NetBios`-имя домена указывается в формате `domain\\user` перед `\\`.
<.> `LdapOptions` -- настройки подключения к LDAP каталогу домена.
<.> `LdapServerAddresses` -- адреса серверов LDAP данного домена. Если адрес соответствует полному имени домену, параметр можно удалить.
<.> `AuthType` -- тип аутентификации в LDAP.
<.> `Credential` -- логин и пароль пользователя для подключения к LDAP-каталогам текущего домена. Пароль для подключения можно зашифровать, см. подробнее в документации по установке системы, раздел "xref:install-linux:ROOT:appendix/account-protection.adoc[]".
<.> `FullDomainName` -- полное имя домена указывается в формате `user@example.com` учётной записи после `@`.
<.> `ChallengeTo` -- настройка позволяет переадресовывать запросы от выбранного домена к каталогам указанного домена, см. <<challengeto,далее>>.

.Раздел `Catalogs` может содержать массив настроек вида:
[source,json]
----
 {
    "FullDomainName": "example.com", <.>
    "NetBiosDomainName": "EXAMPLE", <.>
    "LdapOptions": { <.>
      "LdapServerAddresses": [ "example.com" ], <.>
      "AuthType": "Basic", <.>
      "Port": 389, <.>
      "Credential": { <.>
        "UserName": "user@example.com",
        "Password": "Password"
      }
    }
}
----
<.> `FullDomainName` -- полное имя домена указывается в формате `user@example.com` учётной записи после `@`.
<.> `NetBiosDomainName` -- `NetBios`-имя домена указывается в формате `domain\\user` перед `\\`.
<.> `LdapOptions` -- настройки подключения к LDAP каталогу домена.
<.> `LdapServerAddresses` -- адреса серверов LDAP данного домена. Если адрес соответствует полному имени домену, параметр можно удалить.
<.> `AuthType` -- тип аутентификации в LDAP.
<.> `Port` -- порт подключения к LDAP каталогам, перечисленным в `LdapServerAddresses`.
<.> `Credential` -- логин и пароль пользователя для подключения к LDAP-каталогам текущего домена. Пароль для подключения можно зашифровать, см. подробнее в документации по установке системы, раздел "xref:install-linux:ROOT:appendix/account-protection.adoc[]".

// tag::chalto[]
[#challengeto]
== Настройка "ChallengeTo"

Для большей гибкости предусмотрена настройка `ChallengeTo`, позволяющая переадресовывать запросы от выбранного домена к каталогам указанного домена. Например, если пользователи в домене `example.com`, имеют учётную запись `user@example1.com`, конфигурационный файл можно изменить следующим образом:

[source,json]
----
{
    "FullDomainName": "example1.com",
    "NetBiosDomainName": "example1",
    "ChallengeTo": "example2.com"
}
----

Осуществляется проверка значения, указанного после `@` (для UPN-формата) или до `\` (для NT-формата), проводится поиск соответствия в `Catalogs`. Если у такого соответствия есть `ChallengeTo`, далее аутентификация пользователя будет проверяться по LDAP серверу того каталога, который указан у домена в `ChallengeTo`.

После выполнения вышеуказанной настройки аутентификация и получение информации о пользователе `user@example1.com` будут осуществляться в каталогах домена `example2.com`.

Настройка `ChallengeTo` применима именно при наличии UPN-суффиксов внутри одного домена, если доменов несколько, рекомендуется добавить столько же записей с указанием отдельных LDAP-серверов для этих доменов.

WARNING: При такой настройке существует ограничение. Встроенная (сквозная) аутентификация будет работать только для тех пользователей домена, в который введен сервер на Linux.
// end::chalto[]
