= Особенности хранения архивных данных в {dv}

Архив {dv} предназначен для хранения данных, представляющих интерес для организации, но не используемых в оперативной деятельности.

В зависимости от настроек {dv}, архивные данные могут храниться в основной БД {dv} (таблицы с архивными данными имеют постфикс *_archive*) или в отдельной _архивной базе данных_.

Архивная база данных -- xref:DBExternalTables.adoc[сателлитная база данных] {dv}, которая предназначена для хранения данных архивных карточек. Архивная база данных имеет название: "[Название основной БД {dv}]_Archive".

Использование отдельной БД для хранения архивных карточек позволяет снизить нагрузку на основную БД, облегчить обслуживание основной базы {dv}, сократить время на создание её резервных копий.

Для использования архивной БД лицензия {dv} должна содержать опцию "{dv} Архивная база данных".

Способ хранения архивных данных определяется при создании БД {dv}, и не может быть изменен (без последствий) после создания. Дополнительная информация в пункте xref:DBExternalTables.adoc[Подключение сателлитных баз данных].

Перемещение карточки в архив выполняется при добавлении к ней атрибута "Архивирована" (документ _модуль "{dv} 5. {wincl}". Руководство пользователя_, пункт "Архивирование данных"), а извлечение из архива -- при удалении данного атрибута. Карточки, находящиеся в архиве доступны только для чтения.

Помещать карточки в архив, извлекать карточки из архива, открывать архивированные карточки и находить их с помощью поисковых запросов могут только пользователи, которые включены в следующие группы:

* _{dv} Archive Operators_;
* _{dv} Administrators_;
* _{dv} Security Administrators_;

Для всех остальных пользователей карточки, помещенные в архив, недоступны и не отображаются в клиентских программах. Правом на удаление архивных карточек обладают только пользователи, включённые в группу _{dv} Archive Operators_ (Опреаторы архива).
