= Перенести журналы в сателлитную БД

[WARNING]
====
После создания или подключения БД {dv} запрещается подключать или отключать сателлитные БД, т. к. это может привести к потере данных и неработоспособности системы {dv}.
====

В крайнем случае, воспользуйтесь специальными скриптами, которые предоставляются по запросу. Данные скрипты изменяют место хранения журналов с основной БД на сателлитную.

[NOTE]
====
Основной способ подключения сателлитной БД -- создать её через _{cns}_.
====

. Определите, поддерживает ли Microsoft SQL с БД {dv} функцию секционированияfootnote:[См. описание установленной версии SQL Server.].
. Остановите сервер и сервисы {dv}.
. В SQL Server Management Studio перейдите в БД {dv} и выполните один из следующих скриптов:
+
* Если СУБД поддерживает секционирование -- скрипт из файла xref:attachment$ScriptCreateLogSatellit.sql[ScriptCreateLogSatellit.sql].
* Если СУБД не поддерживает секционирование -- скрипт из файла xref:attachment$ScriptCreateLogSatellitNoPartitions.sql[ScriptCreateLogSatellitNoPartitions.sql].
+
****
Данные скрипты создают сателлитную БД для хранения журналов, а также переименовывают существующие таблицы *dvsys_log* и *dvsys_log_security* в *dvsys_log_local_table* и *dvsys_log_security_local_table* соответственно.

Журнал приложений *dvsys_log_application* содержит историю изменений карточек и остаётся в основной БД.
****
+
. Если нужно перенести существующие журналы в сателлитную БД, выполните в основной БД {dv} скрипт:
+
.Скрипт для переноса существующих журналов в сателлитную БД
[%collapsible]
====
include::partial$excerpts.adoc[tags=replaceName]

[source,sql]
----
insert into [Название-БД-Docsvision_Log].[dbo].[dvsys_log] ([UserID],[EmployeeID],[ComputerName],[ComputerAddress],[Date],[Type],[OperationID],[Code],[TypeID],[ResourceID],[ParentID],[NewResourceID],[ResourceName],[Data])
select [UserID],[EmployeeID],[ComputerName],[ComputerAddress],[Date],[Type],[OperationID],[Code],[TypeID],[ResourceID],[ParentID],[NewResourceID],[ResourceName],[Data] from [Название-БД-Docsvision].[dbo].[dvsys_log_local_table]

insert into [Название-БД-Docsvision_Log].[dbo].[dvsys_log_security] ([UserID],[EmployeeID],[ComputerName],[ComputerAddress],[Date],[OperationID],[Status],[DesiredAccess],[ObjectType],[ObjectID],[LocationID],[PropertyID],[Data])
select [UserID],[EmployeeID],[ComputerName],[ComputerAddress],[Date],[OperationID],[Status],[DesiredAccess],[ObjectType],[ObjectID],[LocationID],[PropertyID],[Data] from [Название-БД-Docsvision].[dbo].[dvsys_log_security_local_table]
----
====
+
. Также в сателлитную БД можно перенести данные из базы данных с архивами журналов -- если в версии модуля 5.5.1 (или ранее) было настроено архивирование журналов в отдельную БД. Для переноса архивных журналов выполните:
+
.Скрипт для переноса архивов журналов в сателлитную БД
[%collapsible]
====
include::partial$excerpts.adoc[tags=replaceName]

[source,sql]
----
insert into [Название-БД-Docsvision_Log].[dbo].[dvsys_log] ([UserID],[EmployeeID],[ComputerName],[ComputerAddress],[Date],[Type],[OperationID],[Code],[TypeID],[ResourceID],[ParentID],[NewResourceID],[ResourceName],[Data])
select [UserID],[EmployeeID],[ComputerName],[ComputerAddress],[Date],[Type],[OperationID],[Code],[TypeID],[ResourceID],[ParentID],[NewResourceID],[ResourceName],[Data] from [{Название БД для архивации логов}].[dbo].[dvsys_log]

insert into [Название-БД-Docsvision_Log].[dbo].[dvsys_log_security] ([UserID],[EmployeeID],[ComputerName],[ComputerAddress],[Date],[OperationID],[Status],[DesiredAccess],[ObjectType],[ObjectID],[LocationID],[PropertyID],[Data])
select [UserID],[EmployeeID],[ComputerName],[ComputerAddress],[Date],[OperationID],[Status],[DesiredAccess],[ObjectType],[ObjectID],[LocationID],[PropertyID],[Data] from [{Название БД для архивации логов}].[dbo].[dvsys_log_security]
----
====
+
.Скрипт для извлечения журналов работы с карточками из архива:
[%collapsible]
====
include::partial$excerpts.adoc[tags=archiveName]

[source,sql]
----
insert into [Название-БД-Docsvision].[dbo].[dvsys_log_application] ([UserID],[EmployeeID],[ComputerName],[ComputerAddress],[Date],[Type],[OperationID],[Code],[TypeID],[ResourceID],[ParentID],[NewResourceID],[ResourceName],[Data])
select [UserID],[EmployeeID],[ComputerName],[ComputerAddress],[Date],[Type],[OperationID],[Code],[TypeID],[ResourceID],[ParentID],[NewResourceID],[ResourceName],[Data] FROM [Название-БД-для-архивации-журналов].[dbo].[dvsys_log_application]
----
====
+
. Запустите сервер и сервисы {dv}.

CAUTION: Если вы переносили журналы в сателлитную БД, убедитесь что данные попали в БД с помощью РМА.
