[[ariaid-title1]]
== Особенности хранения архивных данных в Docsvision

Архив Docsvision предназначен для хранения данных, представляющих интерес для организации, но не используемых в оперативной деятельности.

В зависимости от настроек Docsvision, архивные данные могут храниться в основной БД Docsvision (таблицы с архивными данными имеют постфикс [.keyword]*_archive*) или в отдельной [.dfn .term]_архивной базе данных_.

Архивная база данных – xref:DBExternalTables.adoc[сателлитная база данных] Docsvision, которая предназначена для хранения данных архивных карточек. Архивная база данных имеет название: «[Название основной БД Docsvision]_Archive».

Использование отдельной БД для хранения архивных карточек позволяет снизить нагрузку на основную БД, облегчить обслуживание основной базы Docsvision, сократить время на создание её резервных копий.

Для использования архивной БД лицензия Docsvision должна содержать опцию «Docsvision Архивная база данных».

Способ хранения архивных данных определяется при создании БД Docsvision, и не может быть изменен (без последствий) после создания. Дополнительная информация в пункте xref:DBExternalTables.adoc[Подключение сателлитных баз данных].

Перемещение карточки в архив выполняется при добавлении к ней атрибута «Архивирована» (документ [.ph]#[.dfn .term]_Модуль «Docsvision 5. Windows-клиент». Руководство пользователя_#, пункт «Архивирование данных»), а извлечение из архива – при удалении данного атрибута. Карточки, находящиеся в архиве доступны только для чтения.

Помещать карточки в архив, извлекать карточки из архива, открывать архивированные карточки и находить их с помощью поисковых запросов могут только пользователи, которые включены в следующие группы:

* [.keyword .parmname]_Docsvision Archive Operators_;
* [.keyword .parmname]_Docsvision Administrators_;
* [.keyword .parmname]_Docsvision Security Administrators_;

Для всех остальных пользователей карточки, помещенные в архив, недоступны и не отображаются в клиентских программах. Правом на удаление архивных карточек обладают только пользователи, включённые в группу [.keyword .parmname]_Docsvision Archive Operators_ (Опреаторы архива).

*Parent topic:* xref:../topics/Administrator_functions.adoc[Функции администратора]
