[[ariaid-title1]]
== Отключение полнотекстового индексирования

При отключении БД от сервиса полнотекстового индексирования Docsvision, сервис перестанет передавать данные в систему полнотекстового поиска; в клиентской программе, настроенной на работу с данной БД, будет заблокирована возможность использовать полнотекстовый поиск.

. [.ph .cmd]#Откройте Консоль настройки Docsvision.#
. [.ph .cmd]#Перейдите к элементу [.ph .menucascade]#[.ph .uicontrol]*Модули расширения* > [.ph .uicontrol]*Сервис полнотекстового поиска*#.#
. [.ph .cmd]#Выберите в списке отключаемую базу данных.#
. [.ph .cmd]#Нажмите кнопку [.ph .uicontrol]*Удалить базу данных*, чтобы отключить БД от сервиса полнотекстового индексирования, или кнопку [.ph .uicontrol]*Удалить базу и индексы*, чтобы также удалить из системы полнотекстового поиска построенные индексы.#
+
БД будет отключена от системы полнотекстового индексирования, и удалена из списка баз данных, использующих сервис полнотекстового индексирования.
. [.ph .cmd]#Перезапустите сервер Docsvision (пул приложений «DocsVision» или IIS) и сервис полнотекстового индексирования (службу «Docsvision 5.5 Full-text indexing Service»).#

*Parent topic:* xref:../topics/Preparing_to_Work_Configure_FullText_Search.adoc[Настройка полнотекстового поиска]
