= Журналы системы

В системе {dv} имеется ряд журналов, которые используются для сбора информации о процессе установки и работы системы:

* <<serverLog,Журнал работы сервера>>.
* <<clientLog,Журналы установки клиентских компонентов>>.
* <<consoleLog,Журнал сообщений "Консоли настройки {dv}">>.
* <<searchLog,Журнал сообщений сервиса полнотекстового поиска>>.
* <<fileLog,Журнал работы файлового сервиса>>.

[#serverLog]
== Журнал работы сервера

Данный журнал содержит информацию о работе сервера {dv}. Журнал сервера является средством диагностики при возникновении нештатных ситуаций и предназначен для передачи в службу технической поддержки {dv}.

Путь к журналу указывается в программе _{cns}_ в параметре *Файл журнала* ветки *Сервер* (см. xref:console-server.adoc[Сервер]).

[#clientLog]
== Журналы установки клиентских компонентов

В журналах установки клиентских компонентов фиксируются события, возникающие в процессе установки клиентской части модулей {dv}.

Журнал формируется отдельно для каждого из устанавливаемых клиентских компонентов и сохраняется в текстовый файл.

Путь к папке для хранения журналов всех установленных клиентских компонентов указывается в программе _{cns}_ в параметре *Папка журналов установки* раздела xref:console-config-client.adoc[Настройка клиентской части].

Просмотреть журнал можно, открыв файл в текстовом редакторе.

[#searchLog]
== Журнал сообщений сервиса полнотекстового поиска

xref:search-logging.adoc[Данный журнал] содержит информацию о работе сервиса полнотекстового индексирования {dv}.

[#consoleLog]
== Журнал сообщений "Консоли настройки {dv}"

По умолчанию журнал сообщений программы _{cns}_ не ведётся.

.Ведение журнала можно включить в настройках:
. Откройте _{cns}_.
. В меню выберите menu:Инструменты[Настройки...].
. В окне _Общие настройки_ поставьте флаг `*Журналировать операции консоли настройки*` и укажите путь к файлу журнала в поле _Файл журнала_.

В журнале ведётся протоколирование событий программы _{cns}_ и всех операций, выполняемых через программу.

[#fileLog]
== Журнал работы файлового сервиса

В данный журнал сохраняется информация об ошибках работы файлового сервиса {dv}, а также информационные сообщения (если включено).

Журнал сервера является средством диагностики при возникновении нештатных ситуаций и предназначен для передачи в службу технической поддержки {dv}.

По умолчанию журнал сохраняется в тот же каталог, что и журнал работы сервера {dv}. Подробнее см. в пункте xref:file-service-logging.adoc[Настройка протоколирования работы файлового сервиса {dv}].
