= Настройка внешних хранилищ {dv}

=== Общие сведения

Файлы, сохраняемые в системе {dv}, имеют две составляющие: атрибутивную и бинарную. Атрибутивная часть файла (с атрибутами файла: название, даты создания и изменения, размер) хранится в БД {dv}, бинарная часть (с содержимым файла) может также храниться в БД или во внешнем хранилище следующих типов: файловая система, внешняя БД или FileStream внешней БД, внешние хранилища других типов, для работы с которыми были реализованы программные компоненты (провайдеры к внешним хранилищам).

К серверу {dv} могут быть одновременно подключены несколько хранилищ разных типов. Администратор должен настроить правила, по которым бинарные данные будут распределяться между подключенными хранилищами. Для этого ему предоставляются следующие инструменты:

. Разделы хранилища -- назначаемые внешним хранилищам метки, по которым определяется возможность сохранения бинарных данных файлов в зависимости их оперативного состояния.
+
В {dv} есть следующие типы разделов внешних хранилищ:

* "Основные" -- раздел предназначен для сохранения бинарных данных файлов, не являющихся архивными или временными (см. далее);
* "Архивные" -- раздел предназначен для сохранения бинарных данных файлов карточек, помещенных в архив;
* "Временные" -- раздел предназначен для временного хранения бинарных данных файлов, которые находятся в процессе загрузки в {dv} (но еще не загружены).
. Группа хранилищ -- сущность, объединяющая несколько хранилищ (одного или разных типов), для которой устанавливается правило распределения бинарных данных файлов между хранилищами, входящими в группу.
. Правила помещения в хранилища -- определяет целевую группу хранилищ для сохранения бинарных данных файла в зависимости от параметров сохраняемого файла.
. Группа хранилищ по умолчанию -- определяет целевую группу хранилищ по умолчанию для файлов с определенным оперативным состоянием (основные, архивные, временные). Данная группа хранилищ будет выбрана для сохранения файлов, для которых сервер {dv} не смог определить подходящее правило помещения в хранилища.

=== Алгоритм выбора внешнего хранилища для сохранения бинарных данных файла сервером {dv}

. Проверяется выполнение условий правил помещения в хранилище:
* если условия выполнены -- выбирается группа хранилищ, соответствующая правилу;
* если условия не выполнены -- выбирается группа хранилищ, которая указана по умолчанию для файлов с данным оперативным состоянием (основные, архивные, временные).
. Из выбранной группы хранилищ выбирается хранилище для сохранения данных файла:
[loweralpha]
.. Определяются хранилища, в которые может быть добавлен файл с его классом. Например, если файл является временным, то будут выбраны только хранилища, в которые допускается сохранять временные файлы.
.. Исходя из установленного для группы хранилищ режима выбора выбирается целевое хранилище для сохранения данных файла.
+
*Данные файла размещаются в хранилище при загрузке файла в БД, и не перемещается между хранилищами при создании/изменении хранилищ.*

=== Стандартная последовательность подключения внешнего хранилища

Чтобы подключить внешнее хранилище к серверу {dv}, администратору потребуется:

. Настроить параметры подключения к внешнему хранилищу:
* указать данные для подключения к внешней БД;
* указать путь для сохранения файлов в файловую систему и т.п.
. Создать для хранилища новую группу или включить его в существующую.
. Для новой группы хранилищ настроить правила помещения данных в это хранилище.

* xref:StoragesImportant.adoc[Важные условия настройки внешних хранилищ].* xref:SetupStorage.adoc[Подключение внешнего хранилища].* xref:SetupStorageGroup.adoc[Создание группы хранилищ].* xref:AddStorageToStoragesGroup.adoc[Включение хранилища в группу хранилищ].* xref:SetupStorageRule.adoc[Настройка правила помещения в хранилище].* xref:SetDefaultStorage.adoc[Назначение группы хранилищ по умолчанию].* xref:CreateFileStreamStorage.adoc[Пример. Настройка хранилища файлов в FileStream внешней БД].* xref:CreateFSStorage.adoc[Пример. Настройка хранилища файлов в файловой системе].
