[[ariaid-title1]]
== Настройка протоколирования работы файлового сервиса Docsvision

Работа файлового сервиса Docsvision (служба FileService) протоколируется со следующими параметрами по умолчанию:

* если для сервера Docsvision включено протоколирование работы:
** файл журнала: [.ph .filepath]`<Папка для журналов сервера Docsvision>\FileService.log`;
** уровень логирования: [.ph .filepath]`<уровень логирования сервера>`;
* если для сервера Docsvision НЕ включено протоколирование работы:
** файл журнала: [.ph .filepath]`C:\Program Files (x86)\Docsvision\Platform\5.5\FileService.log`.
** уровень логирования: только ошибки.

Для изменения настроек:

. Добавьте в реестр ОС сервера Docsvision параметры:
* [.ph .filepath]`HKLM\SOFTWARE\DocsVision\Platform\5.5\Server\FileServiceLogFile` – полный путь с именем файла журнала; тип параметра – строковый;
* [.ph .filepath]`HKLM\SOFTWARE\DocsVision\Platform\5.5\Server\FileServiceTraceLevel` – уровень логирования; тип параметра – DWORD32. Возможные уровни логирования:
** 1 – только ошибки;
** 3 – ошибки и информационные сообщения.
. Перезапустите файловый сервис Docsvision.

[NOTE]
====
[.note__title]#Important:# У учетной записи файлового сервиса Docsvision должны быть права на создание, изменение и чтение файла журнала.
====

*Parent topic:* xref:../topics/Administrator_functions.adoc[Функции администратора]
