= Настройка протоколирования работы файлового сервиса {dv}

Работа файлового сервиса {dv} (служба FileService) протоколируется со следующими параметрами по умолчанию:

* если для сервера {dv} включено протоколирование работы:
** файл журнала: [.ph .filepath]`<Папка для журналов сервера {dv}>\FileService.log`;
** уровень логирования: [.ph .filepath]`<уровень логирования сервера>`;
* если для сервера {dv} НЕ включено протоколирование работы:
** файл журнала: [.ph .filepath]`C:\Program Files (x86)\{dv}\Platform\5.5\FileService.log`.
** уровень логирования: только ошибки.

Для изменения настроек:

. Добавьте в реестр ОС сервера {dv} параметры:
* [.ph .filepath]`HKLM\SOFTWARE\DocsVision\Platform\5.5\Server\FileServiceLogFile` – полный путь с именем файла журнала; тип параметра – строковый;
* [.ph .filepath]`HKLM\SOFTWARE\DocsVision\Platform\5.5\Server\FileServiceTraceLevel` – уровень логирования; тип параметра – DWORD32. Возможные уровни логирования:
** 1 – только ошибки;
** 3 – ошибки и информационные сообщения.
. Перезапустите файловый сервис {dv}.

[NOTE]
====
[.note__title]#Important:# У учетной записи файлового сервиса {dv} должны быть права на создание, изменение и чтение файла журнала.
====

