[[ariaid-title1]]
== Особенности настройки кластера сервисов полнотекстового индексирования

Кластер сервисов полнотекстового индексирования может быть организован из нескольких экземпляров сервиса, установленных на разных компьютерах. Данная структура позволяет распределить нагрузку, связанную с получением данных для индексирования, между несколькими узлами.

Для организации кластера сервисов полнотекстового индексирования:

. Настройте экземпляр сервиса полнотекстового индексирования, установленного с Docsvision, стандартным образом, или установите и настройте сервис полнотекстового индексирования xref:InstallFulltextNode.adoc[отдельно от сервера Docsvision].
. xref:InstallFulltextNode.adoc[Установите второй экземпляр сервиса полнотекстового индексирования].
. Внесите изменения в реестр ОС на компьютере второго узла:
[loweralpha]
.. Создайте ветку [.ph .filepath]`HKLM\SOFTWARE\DocsVision\Platform\5.5\Server\Databases`.
.. Скопируйте в ветку параметры из аналогичной ветки реестра ОС Windows компьютера, на котором установлен сервер Docsvision, данные которого индексируются. Копируемые параметры содержат информацию о БД Docsvision.
. Перезапустите службу «Docsvision 5.5 Full-text indexing Service» на созданном узле кластера.
. Если требуется, создайте и настройте другие узлы кластера аналогичным образом.

*Parent topic:* xref:../topics/Preparing_to_Work_Configure_FullText_Search.adoc[Настройка полнотекстового поиска]
