[[ariaid-title1]]
== Изменение настроек полнотекстового поиска

Для изменения настроек полнотекстового поиска выполните следующие действия:

. [.ph .cmd]#Откройте Консоль настройки Docsvision.#
. [.ph .cmd]#Перейдите к элементу [.ph .menucascade]#[.ph .uicontrol]*Модули расширения* > [.ph .uicontrol]*Сервис полнотекстового поиска*#.#
. [.ph .cmd]#Выберите в списке базу данных, настройки индексирования которой следует изменить.#
. [.ph .cmd]#Нажмите кнопку [.ph .uicontrol]*Свойства индексирования*.#
+
Будет открыто окно настройки полнотекстового индексирования.
. [.ph .cmd]#Измените настройки.#
+
* Описание настроек индексирования в SQL Server приведено в пункте xref:FulltextReconfigureMSSQL.adoc[Изменение настроек полнотекстового поиска SQL Server].
* Описание настроек индексирования в Elasticsearch приведено в пункте xref:FulltextReconfigureElastic.adoc[Изменение настроек полнотекстового поиска Elasticsearch].
. [.ph .cmd]#Нажмите кнопку [.ph .uicontrol]*Применить*, чтобы применить измененные настройки.#
. [.ph .cmd]#Перезапустите сервис полнотекстового индексирования (службу «Docsvision 5.5 Full-text indexing Service») и сервер Docsvision (пул приложений «DocsVision» или IIS).#

* *xref:../topics/FulltextReconfigureMSSQL.adoc[Изменение настроек полнотекстового поиска SQL Server]* +
* *xref:../topics/FulltextReconfigureElastic.adoc[Изменение настроек полнотекстового поиска Elasticsearch]* +

*На уровень выше:* xref:../topics/Preparing_to_Work_Configure_FullText_Search.adoc[Настройка полнотекстового поиска]
