= Особенности настройки кластера сервисов полнотекстового индексирования

Сервис полнотекстового индексирования может быть организован из нескольких экземпляров сервиса на нескольких компьютерах в кластере. Данная структура позволяет распределить нагрузку, связанную с получением данных для индексирования, между несколькими узлами.

.Чтобы организовать кластер сервисов полнотекстового индексирования:
. Настройте экземпляр сервиса полнотекстового индексирования, установленного с {dv}, стандартным образом, или установите и настройте сервис полнотекстового индексирования xref:fullTextSeparateInstall.adoc[отдельно от сервера {dv}].
. xref:fullTextSeparateInstall.adoc[Установите второй экземпляр сервиса полнотекстового индексирования].
. Внесите изменения в реестр ОС на компьютере второго узла:
[lowerroman]
.. Создайте ветку `HKLM\SOFTWARE\DocsVision\Platform\5.5\Server\Databases`.
.. Скопируйте в ветку параметры из аналогичной ветки реестра сервера {dv}, данные которого индексируются. Копируемые параметры содержат информацию о БД {dv}.
. Перезапустите службу _{fts}_ на созданном узле кластера.
. Если требуется, создайте и настройте другие узлы кластера аналогичным образом.
