= Добавление пользователей {dv}

. Авторизоваться в {dv} может любой пользователь, учетная запись которого включена в одну из xref:Appendix_A.adoc[групп безопасности, созданных модулем]. По умолчанию все пользователи (Everyone) включены в группу безопасности "{dv} Users".
. Работать с данными системы {dv} могут пользователи, которым предоставлены права на уровне модели безопасности, которая ограничивает доступ к объекту:
* дискреционная и мандатная -- модели безопасности, предоставляемые данным модулем;
* ролевая -- модель безопасности, предоставляемая модулем "{dv} 5. Базовые объекты".
+
Настройка прав по дискреционной модели безопасности осуществляется в {wincl}е/РМА (документ _модуль "{dv} 5. {wincl}". Руководство пользователя_, раздел "Управление доступом к объектам").
+
Права доступа по ролевой модели безопасности не назначаются напрямую, а вычисляются в контексте работы с объектом. Настройка ролевой модели безопасности рассмотрена в документе _модуль "{dv} 5. Базовые объекты". Руководство администратора_, раздел "Конструктор ролей". Для работы с правилами ролевой модели пользователь должен быть зарегистрирован в _Справочнике сотрудников_.
