[[ariaid-title1]]
== Настройка учетных записей сервисов Docsvision

Серверная часть модуля «Платформа» устанавливает в ОС Windows собственные сервисы:

. Сервер Docsvision (включает службу «Docsvision 5.5 Storage Server» и веб-приложение сервера Docsvision, размещенное в IIS) – обеспечивает возможность подключения клиентских приложений.
. Сервис полнотекстового индексирования «Docsvision 5.5 Full-Text Indexing Service» – обеспечивает индексацию данных в БД Docsvision.
. Файловый сервис «Docsvision 5.5 File Service» – удаляет файлы из хранилища бинарных данных файлов, а также переносит бинарные данные файлов из одного хранилища в другое.

Администратор должен самостоятельно настроить права учетных записей служб Docsvision. Требования учетных записей сервисов Docsvision приведены в xref:Appendix_B.adoc[Приложении B].

Рекомендуется xref:AssignmentofVipLicense.adoc[назначить персональную лицензию] учетной записи указанных сервисов.

*Parent topic:* xref:../topics/PreparationToWork.adoc[Подготовка к работе]
