[[ariaid-title1]]
== Добавление пользователей Docsvision

. Авторизоваться в Docsvision может любой пользователь, учетная запись которого включена в одну из xref:Appendix_A.adoc[групп безопасности, созданных Модулем]. По умолчанию все пользователи (Everyone) включены в группу безопасности «Docsvision Users».
. Работать с данными системы Docsvision могут пользователи, которым предоставлены права на уровне модели безопасности, которая ограничивает доступ к объекту:
* дискреционная и мандатная – модели безопасности, предоставляемые данным Модулем;
* ролевая – модель безопасности, предоставляемая модулем «Docsvision 5. Базовые объекты».
+
Настройка прав по дискреционной модели безопасности осуществляется в Windows-клиенте/РМА (документ [.ph]#[.dfn .term]_Модуль «Docsvision 5. Windows-клиент». Руководство пользователя_#, раздел «Управление доступом к объектам»).
+
Права доступа по ролевой модели безопасности не назначаются напрямую, а вычисляются в контексте работы с объектом. Настройка ролевой модели безопасности рассмотрена в документе [.ph]#[.dfn .term]_Модуль «Docsvision 5. Базовые объекты». Руководство администратора_#, раздел «Конструктор ролей». Для работы с правилами ролевой модели пользователь должен быть зарегистрирован в [.dfn .term]_Справочнике сотрудников_.

*На уровень выше:* xref:../topics/UsersMore.adoc[Управление пользователями]
