[[ariaid-title1]]
== Установка клиентской части Модуля

Клиентская часть модуля «Платформа» должна быть установлена на компьютеры пользователей Docsvision.

Модуль «Платформа» может быть установлен двумя способами:

* с сервера Docsvision – требуемые компоненты будут загружены с сервера Docsvision и установлены автоматически;
* из пакета установки (вручную) – администратор должен самостоятельно установить клиентскую часть модуля «Платформа».

Данный компонент может быть установлен для текущего пользователя или для всех пользователей компьютера. Область установки выбирается с помощью:

* настройки [.ph .menucascade]#[.ph .uicontrol]*Консоль настройки Docsvision* > [.ph .uicontrol]*Настройки сервера* > [.ph .uicontrol]*Настройка клиентской части* > [.ph .uicontrol]*Область установки*# – если компоненты устанавливаются с сервера Docsvision;
* при установке – если компоненты устанавливаются вручную.

* *xref:../topics/Install_client_fromserver.adoc[Установка клиентской части модуля «Платформа» с сервера Docsvision]* +
* *xref:../topics/Install_client_frommsi.adoc[Установка клиентской части модуля «Платформа» из установочного пакета]* +

*Parent topic:* xref:../topics/Install_and_configuration.adoc[Установка и настройка Модуля]
