= Установка модуля {pl}

Система поддерживает установку на Linux с ограничениями доступной функциональности. Подробнее см. руководство по установке, раздел "xref:6.1@install-linux::linux-limitations.adoc[]".

// tag::platform-and-windows[]
[#install]
== Установка модуля {pl} на Linux

Установите серверные компоненты модуля.

ifndef::upgrade[]
Все описанные ниже команды необходимо выполнять после завершения xref:pre-config-server.adoc[предварительной настройки сервера].
endif::[]
ifdef::upgrade[]
Все описанные ниже команды необходимо выполнять после завершения <<preconfig,предварительной настройки сервера>>.
endif::[]

При установке модулей {dv} в ОС Linux необходимо установить модули описанными далее командами. Также потребуется установка серверных компонентов на ОС Windows для работы с программой {cns}. Установка клиентской части на ОС Windows потребуется только в случае установки {wincl}а.

. Установите службу модуля {pl} следующей командой, предварительно обновив индекс пакетов:
+
[source,bash]
----
sudo apt-get update
sudo apt-get install docsvision-platform
----
+
ifndef::upgrade[]
. Активируйте лицензию при помощи xref:activation.adoc[утилиты активации]:
endif::[]
ifdef::upgrade[]
. Активируйте лицензию при помощи утилиты активации. См. подробнее в документации по установке системы, раздел xref:6.1@install-linux::activation.adoc[]:
endif::[]
+
[source,bash]
----
sudo apt-get install docsvision-activation
cd /usr/lib/docsvision/tools/activation
sudo ./activation online YOUR-KEY
----
+
. Замените или отредактируйте файл настроек модуля:
+
[source,bash]
----
sudo cp ~/tech_days/Platform/appsettings.json /usr/lib/docsvision/Platform/appsettings.json
----
+
. Запустите службу модуля командой:
+
[source,bash]
----
sudo systemctl start platform
----
+
. После установки платформы установите остальные модули по инструкции, приведённой ниже.

[#windows]
== Установка серверных компонентов на Windows

****
Установка серверных компонентов на Windows необходима для работы Консоли управления и настройки БД. Более подробная информация по установке приведена в руководстве по установке системы, раздел "xref:6.1@install-linux::install-quick-ref.adoc[]".
****

include::installguide:ROOT:partial$doNotStart.adoc[]

Пользователь, выполняющий установку, должен обладать правами администратора.

[NOTE]
====
Включить журналирование процесса установки можно с помощью флага `*/l*v*`:

[source]
----
msiexec /i "Docsvision 5 Platform server.msi" /l*v install.log
----
====

include::6.1@install-linux::install-other-windows.adoc[tags=other-windows]
