[[ariaid-title1]]
== Ограничение размера файлового кэша

Сервер Docsvision кэширует файлы запрашиваемые клиентами в папку [.ph .filepath]`C:\Windows\TEMP\<Название БД>\FileCache`.

Разрастание кэша ограничивается двумя параметрами:

* `FileCacheSize` – устанавливает максимальный размер кэша от общего размера диска (не свободного места), на котором размещается кэш. Значение задаётся в процентах: от 0 до 100. По умолчанию – 10%.
* `FileCacheMaxFilesCount` – устанавливает максимальное количество файлов в файловом кэше. По умолчанию – 1000 файлов.

Очистка файлового кэша выполняется при запуске IIS и при чтении файла: если превышено значение `FileCacheSize` или `FileCacheMaxFilesCount`.

Администратор может изменить установленные ограничения:

. Откройте реестр ОС на сервере Docsvision.
. Перейдите в раздел [.ph .filepath]`HKLM\SOFTWARE\DocsVision\Platform\5.5\Server`.
. Измените значение параметров `FileCacheSize` и/или `FileCacheMaxFilesCount`.
+
Если параметр(ы) отсутствует – создайте:

* тип параметра: DWORD;
* название: «FileCacheSize» или «FileCacheMaxFilesCount»;
* значение:
** для FileCacheSize – от 0 до 100;
** для FileCacheMaxFilesCount – от 0.

*Parent topic:* xref:../topics/Administrator_functions.adoc[Функции администратора]
