= Настройка режима локализации полей

В системе {dv} поддерживается возможность установки для полей локализованных значений. Фактическое возвращаемое сервером значение поля определяется локалью клиентского приложения.

Системная функция локализации полей используется для локализации следующих элементов:

* названий папок;
* названий представлений и групп представлений, названий столбцов и текста в строках агрегации значений в представлениях;
* названий поисковых запросов и групп запросов.

Функция локализации полей работает следующим образом:

* запустить {wincl} с текущей локалью и задать имя объекта из списка в описании функции;
* затем запустить {wincl} с другой локалью и задать имя на этот же объект на другом языке;
* каждой локали, заданной в {wincl}е, будет соответствовать имя объекта на своём языке. Если локализованное значение отсутствует, будет возвращено значение для локали по умолчанию.

По умолчанию используются следующие настройки локализации полей:

* *функция локализации полей отключена*;
* язык локализации по умолчанию -- 1049 (русский).

[NOTE]
====
[.note__title]#Important:# Для хранения локализованных значений поля используется отдельная секция. На чтение секции потребуется дополнительное время. Это влияет на скорость работы с данными. Значение поля для основной локали хранится в основной секции. Доступ к основной секции осуществляется в обычном режиме и не влияет на скорость работы с данными.
====

Для изменения настроек режима локализации полей по умолчанию:

. Откройте редактор реестра на компьютере с сервером {dv}.
. Перейдите в ветку `HKLM\SOFTWARE\DocsVision\Platform\5.5\Server`.
. Для изменения языка локализации по умолчанию, измените значение параметра "MainLocaleID" на:
* 1049 -- русский,
* 1033 -- английский.
+
Если параметр отсутствует -- добавьте самостоятельно. Тип параметра "MainLocaleID": DWORD.
. Для изменения режима локализации, измените значение параметра "LocalizationMode" на:
* 0 -- режим локализуемых полей выключен;
* 1 -- только чтение локализуемых полей;
* 2 -- только запись локализуемых полей;
* 3 -- режим локализуемых полей включен;
* 4 -- режим локализуемых полей включен с особым режимом: новое значение поля будет сохраняться и для основной локали и для локали клиентского приложения.
+
Если параметр отсутствует -- добавьте самостоятельно. Тип параметра "LocalizationMode": DWORD.
. Перезапустите сервер {dv}.
. Если система {dv} работает в кластере, аналогичные изменения *нужно выполнить на всех серверах {dv} кластера*.
