= Журналы системы

В системе {dv} имеется ряд журналов, которые используются для сбора информации о процессе установки и работы системы:

* <<server,Журнал работы сервера>>.
* <<client,Журналы установки клиентских компонентов>>.
* <<console,Журнал сообщений "Консоли настройки {dv}">>.
* <<search,Журнал сообщений сервиса полнотекстового поиска>>.
* <<file,Журнал работы файлового сервиса>>.

[#server]
== Журнал работы сервера

Данный журнал содержит информацию о работе сервера {dv}. Журнал сервера является средством диагностики при возникновении нештатных ситуаций и предназначен для передачи в службу технической поддержки {dv}.

Путь к журналу указывается в программе _{cns}_ в параметре *Файл журнала* ветки *Сервер* (см. xref:console-server.adoc[Сервер]).

.Если доступ на запись в директорию по умолчанию отсутствует, будет формироваться два журнала сервера:
* В журнал по пути `C:\Users\Administrator\AppData\Local\DocsVision\Logs\Server` будут попадать все ошибки службы *{sss}*.
* В журнал по пути `C:\Windows\System32\config\systemprofile\AppData\Local\Docsvision\Logs\Server` будут попадать ошибки web-сервиса IIS.

[#client]
== Журналы установки клиентских компонентов

В журналах установки клиентских компонентов фиксируются события, возникающие в процессе установки клиентской части модулей {dv}.

Журнал формируется отдельно для каждого из устанавливаемых клиентских компонентов и сохраняется в текстовый файл.

Путь к папке для хранения журналов всех установленных клиентских компонентов указывается в программе _{cns}_ в параметре *Папка журналов установки* раздела xref:console-config-client.adoc[Настройка клиентской части].

Просмотреть журнал можно, открыв файл в текстовом редакторе.

[#search]
== Журнал сообщений сервиса полнотекстового поиска

xref:search-logging.adoc[Данный журнал] содержит информацию о работе сервиса полнотекстового индексирования {dv}.

[#console]
== Журнал сообщений "Консоли настройки {dv}"

По умолчанию журнал сообщений программы _{cns}_ не ведётся.

.Ведение журнала можно включить в настройках:
. Откройте _{cns}_.
. В меню выберите menu:Инструменты[Настройки...].
. В окне _Общие настройки_ поставьте флаг `*Журналировать операции консоли настройки*` и укажите путь к файлу журнала в поле _Файл журнала_.

В журнале ведётся протоколирование событий программы _{cns}_ и всех операций, выполняемых через программу.

[#file]
== Журнал работы файлового сервиса

В данный журнал сохраняется информация об ошибках работы файлового сервиса {dv}, а также информационные сообщения (если включено).

Журнал сервера является средством диагностики при возникновении нештатных ситуаций и предназначен для передачи в службу технической поддержки {dv}.

По умолчанию журнал сохраняется в тот же каталог, что и журнал работы сервера {dv}. Подробнее см. в пункте xref:file-service-logging.adoc[Настройка протоколирования работы файлового сервиса {dv}].
