= Управление пользователями

[CAUTION]
====
Пароль пользователя не должен содержать https://docs.microsoft.com/en-us/sql/relational-databases/security/strong-passwords?view=sql-server-2017[недопустимые символы]: `[`, `]`, `{`, `}`, `(`, `)`, `,`, `;`, `?`, `*`, `!`, `@`, `=`, `"` или `'`.

Пользователь с паролем, содержащим недопустимые символы, не сможет подключиться и войти в систему {dv} с использованием простой аутентификации (с вводом логина и пароля).
====

[#addAdmin]
== Добавление администраторов {dv}

. Добавьте пользователя в группу безопасности *{dv-admins-serv}* на сервере {dv}.
. Если данный пользователь авторизован в ОС на компьютере с сервером {dv}, он должен повторно авторизоваться в ОС, чтобы изменения применились.

== Добавление пользователей {dv}

. Авторизоваться в {dv} может любой пользователь, учетная запись которого включена в одну из xref:security-groups.adoc[групп безопасности, созданных модулем].
+
По умолчанию все пользователи (Everyone) включены в группу безопасности _{dv} Users_.
+
. Работать с данными системы {dv} могут пользователи, которым предоставлены права на уровне модели безопасности. Модель безопасности используется для ограничения доступа к объекту:
* Дискреционная и мандатная -- модели безопасности, предоставляемые модулем {pl}.
* Ролевая -- модель безопасности, предоставляемая модулем _{bo}_.
+
Настройка прав согласно *дискреционной* модели безопасности осуществляется в {wincl}е или РМА (подробнее см. документ Руководство пользователя модуля {wincl}, раздел _Управление доступом к объектам_).
+
Права доступа согласно *ролевой* модели безопасности не назначаются напрямую, а вычисляются в контексте работы с объектом.
+
Настройка ролевой модели безопасности рассмотрена в xref:backofficedesdirs:roles/designer.adoc[документации] модуля _{bo}_. Чтобы работать с правилами ролевой модели, пользователь должен быть зарегистрирован в _Справочнике сотрудников_.
