= Изменение места хранения журналов с основной БД на сателлитную

После создания/подключения БД {dv} запрещается изменять конфигурацию сателлитных БД (подключать/отключать), т. к. это может привести к потере данных и работоспособности системы {dv}.

В крайнем случае, можно воспользоваться специальными скриптами, которые предоставляются вместе к пакетом установки модуля {pl}. Данные скрипты предназначены для изменения места хранения журналов (ТОЛЬКО ЖУРНАЛОВ) с основной БД на сателлитную.

[NOTE]
====
Основным способом подключения сателлитной БД является её создании при создании БД {dv} из Консоли настройки {dv}.
====

. Определите поддерживает ли Microsoft SQL с БД {dv} функцию секционированияxref:#fntarg_1[^1^].
. Остановите сервер и сервисы {dv}.
. В SQL Server Management Studio перейдите в БД {dv} и выполните скрипт из комплекта поставки:
* если СУБД поддерживает секционирование -- скрипт из файла `ScriptCreateLogSatellit.sql`;
* если СУБД НЕ поддерживает секционирование -- скрипт из файла `ScriptCreateLogSatellitNoPartitions.sql`.
+
Данные скрипты создают сателлитную БД для хранения журналов, а также переименовывают существующие таблицы "dvsys_log" и "dvsys_log_security" в "dvsys_log_local_table" и "dvsys_log_security_local_table".
+
Журнал приложений "dvsys_log_application" (содержит историю изменений карточек) остаётся в основной БД.
. Если нужно перенести существующие журналы в сателлитную БД, выполните в основной БД {dv} скрипт:
+
[source]
----
insert into [{Название БД {dv}}_Log].[dbo].[dvsys_log] ([UserID],[EmployeeID],[ComputerName],[ComputerAddress],[Date],[Type],[OperationID],[Code],[TypeID],[ResourceID],[ParentID],[NewResourceID],[ResourceName],[Data])
select [UserID],[EmployeeID],[ComputerName],[ComputerAddress],[Date],[Type],[OperationID],[Code],[TypeID],[ResourceID],[ParentID],[NewResourceID],[ResourceName],[Data] from [{Название БД {dv}}].[dbo].[dvsys_log_local_table]

insert into [{Название БД {dv}}_Log].[dbo].[dvsys_log_security] ([UserID],[EmployeeID],[ComputerName],[ComputerAddress],[Date],[OperationID],[Status],[DesiredAccess],[ObjectType],[ObjectID],[LocationID],[PropertyID],[Data])
select [UserID],[EmployeeID],[ComputerName],[ComputerAddress],[Date],[OperationID],[Status],[DesiredAccess],[ObjectType],[ObjectID],[LocationID],[PropertyID],[Data] from [{Название БД {dv}}].[dbo].[dvsys_log_security_local_table]
----
+
*Вместо "\{Название БД {dv}}" нужно указать название БД {dv}.*
. Также в сателлитную БД можно перенести данные из базы данных с архивами журналов -- если в версии модуля 5.5.1 (или ранее) было настроено архивирование журналов в отдельную БД. Для переноса архивных журналов выполните:
+
[source]
----
insert into [{Название БД {dv}}_Log].[dbo].[dvsys_log] ([UserID],[EmployeeID],[ComputerName],[ComputerAddress],[Date],[Type],[OperationID],[Code],[TypeID],[ResourceID],[ParentID],[NewResourceID],[ResourceName],[Data])
select [UserID],[EmployeeID],[ComputerName],[ComputerAddress],[Date],[Type],[OperationID],[Code],[TypeID],[ResourceID],[ParentID],[NewResourceID],[ResourceName],[Data] from [{Название БД для архивации логов}].[dbo].[dvsys_log]

insert into [{Название БД {dv}}_Log].[dbo].[dvsys_log_security] ([UserID],[EmployeeID],[ComputerName],[ComputerAddress],[Date],[OperationID],[Status],[DesiredAccess],[ObjectType],[ObjectID],[LocationID],[PropertyID],[Data])
select [UserID],[EmployeeID],[ComputerName],[ComputerAddress],[Date],[OperationID],[Status],[DesiredAccess],[ObjectType],[ObjectID],[LocationID],[PropertyID],[Data] from [{Название БД для архивации логов}].[dbo].[dvsys_log_security]
----
+
И извлеките из архива журналы работы с карточками:

[source]
----
insert into [{Название БД {dv}}].[dbo].[dvsys_log_application] ([UserID],[EmployeeID],[ComputerName],[ComputerAddress],[Date],[Type],[OperationID],[Code],[TypeID],[ResourceID],[ParentID],[NewResourceID],[ResourceName],[Data])
select [UserID],[EmployeeID],[ComputerName],[ComputerAddress],[Date],[Type],[OperationID],[Code],[TypeID],[ResourceID],[ParentID],[NewResourceID],[ResourceName],[Data] FROM [{Название БД для архивации логов}].[dbo].[dvsys_log_application]
----
. Запустите сервер и сервисы {dv}.

Если существующие журналы были перенесены в сателлитную БД, убедитесь что данные попали в неё (с помощью РМА).

xref:#fnsrc_1[^1^] См. описание установленной версии SQL Server.
