[[ariaid-title1]]
== PostgreSQL. Перенос БД Docsvision на другой сервер

После переноса БД Docsvision на другой сервер PostgreSQL необходимо подготовить БД к работе, обновив адрес СУБД в конфигурации БД. Данная операция – выполняется после переподключения БД к Консоли настройки Docsvision – может быть выполнена двумя способами.

* Обновление БД с помощью Консоли настройки Docsvision.
. Выполните скрипт в БД Docsvision:
+
[source,pre,codeblock]
----
update dvsys_libraries
set "SysVersion" = "SysVersion" - 1
where "ID" = '26dbf2c0-e72e-4e9e-ab99-816758387ae2'::uuid
----
+
Данный скрипт понизит внутреннюю версию БД для возможности выполнения следующего шага.
. Обновите БД используя функцию обновления Мастера баз данных Консоли настройки Docsvision.
* Обновление адреса с помощью скрипта.
+
Выполните в БД Docsvision один или несколько из следующих скриптов в зависимости от задачи:

[source,pre,codeblock]
----
select * from dvsys_setting_set('JOB_HOST_IP'::text, 'IP'::text); --Если изменился IP сервера БД
select * from dvsys_setting_set('JOB_HOST_NAME'::text, 'host name'::text); --Если изменилось имя сервера БД
select * from dvsys_setting_set('JOB_HOST_PORT'::text, 'port'::text); --Если изменился номер порта
select * from dvsys_setting_set('JOB_HOST_SSPI'::text, 'true/false'::text); --Если изменился способ подключения (встроенная/логин и пароль, true/false соответственно)
select * from dvsys_setting_set('JOB_HOST_USER'::text, 'UserName'::text); --Если изменилось имя пользователя
select * from dvsys_setting_set('JOB_HOST_PASSWORD'::text, 'Password'::text); --Если изменился пароль
----
+
Перед выполнением скрипта измените второй параметр, передаваемый в функцию `dvsys_setting_set`. Например, для изменения IP адреса СУБД на 192.168.2.22 выполните скрипт:

[source,pre,codeblock]
----
select * from dvsys_setting_set('JOB_HOST_IP'::text, '192.168.2.22'::text)
----

*Parent topic:* xref:../topics/Administrator_functions.adoc[Функции администратора]
