[[ariaid-title1]]
== Запуск Консоли настройки Docsvision

Пользователь, запускающий программу «Консоль настройки Docsvision», должен обладать следующими привилегиями:

* быть администратором компьютера, на котором установлена серверная часть модуля «Платформа»;
* входить в группу безопасности [.keyword .parmname]_Docsvision Administrators_ (описание приведено в xref:Appendix_A.adoc[Приложении A]). Пользователь, выполнивший первоначальную настройку Docsvision, автоматически добавляется в группу [.keyword .parmname]_Docsvision Administrators_. Чтобы добавить нового администратора Docsvision следуйте инструкции xref:AddAdministrator.adoc[Добавление администраторов Docsvision];
* для обновления приложений также нужно быть членом групп Docsvision: «Администраторы УД», «Администраторы КС», «Системная для WF»;
* иметь полный доступ к БД Docsvision и обладать административными правами в СУБД, если БД подключена с использованием аутентификации Windows.

Консоль настройки Docsvision может быть запущена в одном из двух режимов:

* обычный режим работы – программа предоставляет доступ ко всем настройкам сервера Docsvision;
* режим мастера настройки – программа предоставляет последовательный доступ к определенным настройкам сервера Docsvision.

Для запуска Консоли настройки Docsvision в обычном режиме используйте ярлык «Server Console» (меню «Пуск») или запустите файл [.ph .filepath]`C:\Program Files (x86)\Docsvision\Platform\5.5\Tools\ServerConsole.exe"`.

Для запуска Консоли настройки Docsvision в режиме мастера, запустите программу с ключом [.keyword]*/w*:

[source,pre,codeblock]
----
"C:\Program Files (x86)\Docsvision\Platform\5.5\Tools\ServerConsole.exe" /w
----

Для запуска Консоли настройки Docsvision в режиме мастера с протоколированием работы, запустите программу с параметрами [.keyword]*/l* (включает журналирование) и [.keyword]*/lp* (передает путь к файлу журнала):

[source,pre,codeblock]
----
"C:\Program Files (x86)\Docsvision\Platform\5.5\Tools\ServerConsole.exe" /w /l /lp:c:\logs\console.log
----

[NOTE]
====
[.note__title]#Note:#

Полный список ключей для запуска Консоли настройки Docsvision:

* /s – запустить приложение без UI;
* /r – удалить конфигурацию Docsvision с сервера;
* /f – запустить консоль настройки в полном режиме;
* /w – запустить консоль настройки в мастер-режиме;
* /l – записывать сообщения в лог-файл;
* /lp <значение> – путь к лог-файлу;
* /reg <значение> – путь к файлу, содержащему настройки сервера Docsvision;
* /rs – удалить конфигурацию модуля расширения;
* /c – настроить Модуль расширения;
* /n <значение> – псевдоним Модуля расширения (совпадает с именем ключа в реестре) для удаления или конфигурации;
* /p <значение> – путь к Модулю расширения для удаления или конфигурации;
* /t <значение> – класс, который нужно создать при загрузке Модуля расширения;
* /help – вывод информационного окна со списком параметров;
* /ln <значение> – язык Консоли (/ln ru – русская версия, /ln en – английская версия; при наличии ресурсов ключи для других версий формируются аналогично).

Описание Консоли настройки Docsvision в режиме мастера настройки приведено в пункте xref:ConfigMaster.adoc[Первоначальная настройка Docsvision]. Описание Консоли настройки Docsvision в обычном режиме работы приведено далее.
====

*Parent topic:* xref:../topics/Server_Console.adoc[Консоль настройки Docsvision]
