= Запуск Консоли настройки {dv}

Пользователь, запускающий программу "Консоль настройки {dv}", должен обладать следующими привилегиями:

* быть администратором компьютера, на котором установлена серверная часть модуля {pl};
* входить в группу безопасности [.keyword .parmname]_{dv} Administrators_ (описание приведено в xref:Appendix_A.adoc[Приложении A]). Пользователь, выполнивший первоначальную настройку {dv}, автоматически добавляется в группу [.keyword .parmname]_{dv} Administrators_. Чтобы добавить нового администратора {dv} следуйте инструкции xref:AddAdministrator.adoc[Добавление администраторов {dv}];
* для обновления приложений также нужно быть членом групп {dv}: "Администраторы УД", "Администраторы КС", "Системная для WF";
* иметь полный доступ к БД {dv} и обладать административными правами в СУБД, если БД подключена с использованием аутентификации Windows.

Консоль настройки {dv} может быть запущена в одном из двух режимов:

* обычный режим работы – программа предоставляет доступ ко всем настройкам сервера {dv};
* режим мастера настройки – программа предоставляет последовательный доступ к определенным настройкам сервера {dv}.

Для запуска Консоли настройки {dv} в обычном режиме используйте ярлык "Server Console" (меню "Пуск") или запустите файл `C:\Program Files (x86)\{dv}\Platform\5.5\Tools\ServerConsole.exe"`.

Для запуска Консоли настройки {dv} в режиме мастера, запустите программу с ключом */w*:

[source,pre,codeblock]
----
"C:\Program Files (x86)\{dv}\Platform\5.5\Tools\ServerConsole.exe" /w
----

Для запуска Консоли настройки {dv} в режиме мастера с протоколированием работы, запустите программу с параметрами */l* (включает журналирование) и */lp* (передает путь к файлу журнала):

[source,pre,codeblock]
----
"C:\Program Files (x86)\{dv}\Platform\5.5\Tools\ServerConsole.exe" /w /l /lp:c:\logs\console.log
----

[NOTE]
====
[.note__title]#Note:#

Полный список ключей для запуска Консоли настройки {dv}:

* /s – запустить приложение без UI;
* /r – удалить конфигурацию {dv} с сервера;
* /f – запустить консоль настройки в полном режиме;
* /w – запустить консоль настройки в мастер-режиме;
* /l – записывать сообщения в лог-файл;
* /lp <значение> – путь к лог-файлу;
* /reg <значение> – путь к файлу, содержащему настройки сервера {dv};
* /rs – удалить конфигурацию модуля расширения;
* /c – настроить модуль расширения;
* /n <значение> – псевдоним модуля расширения (совпадает с именем ключа в реестре) для удаления или конфигурации;
* /p <значение> – путь к модулю расширения для удаления или конфигурации;
* /t <значение> – класс, который нужно создать при загрузке модуля расширения;
* /help – вывод информационного окна со списком параметров;
* /ln <значение> – язык Консоли (/ln ru – русская версия, /ln en – английская версия; при наличии ресурсов ключи для других версий формируются аналогично).

Описание Консоли настройки {dv} в режиме мастера настройки приведено в пункте xref:ConfigMaster.adoc[Первоначальная настройка {dv}]. Описание Консоли настройки {dv} в обычном режиме работы приведено далее.
====

