= Оптимизация производительности

=== Оптимизация базы данных при работе с представлениями

Максимальную нагрузку на сервер в {dv} вызывают операции поиска данных и формирования представлений. Причем, максимальную нагрузку вызывает именно выполнение операций SQL, а не обработка их результатов.

Исходя из этого, повышение общей производительности сервера рекомендуется начинать с настройки базы данных. Поскольку нагрузка на нее очень сильно зависит от специфики конкретного окружения и выполняемых операций, то рекомендации по оптимизации могут быть даны только в индивидуальном порядке.

Основным способом такой оптимизации можно считать создание индексов на полях таблиц, с которыми идет наиболее интенсивная работа. Эти таблицы можно выявить профилированием базы данных (при помощи SQL Profiler) и последующим анализом полученных журналов (SQL 2005 может выполнить такой анализ автоматически и самостоятельно выявить таблицы, нуждающиеся в оптимизации).

Также  в настройках базы данных рекомендуется отключить опцию _Autoshrink_, предназначенную для работы одноименного фонового процесса. Если использование опции необходимо, следует запускать процесс во время технологического обслуживания базы данных.

[NOTE]
====
[.note__title]#Прим.:# _Autoshrink_ предназначен для сокращения размеров базы (файлов), однако, во время работы он  увеличивает нагрузку на ЦП, диски, увеличивает фрагментацию файлов БД, ухудшает состояние индексов и может стать причиной взаимных и даже мертвых блокировок в пользовательских (не системных) транзакциях.
====

=== Кэширование прав доступа

_{dv}_ может кэшировать результаты расчета прав доступа пользователя к карточке, что может дать небольшой положительный эффект в случае многократной проверки прав на чтение или запись. Сохраненные в кэше данные являются действительными в течение определенного промежутка времени, и удаляются при изменении карточки.

Данный механизм управляется значениями ключей, расположенных в ветке `HKLM\Software\{dv}\Platform\5.5\Server` реестра:

* UseAccessCache (типа DWORD):
** 0 -- кэш выключен (по умолчанию).
** 1 -- включен.
* AccessCacheTimeout (типа DWORD) -- интервал времени (в миллисекундах), когда кэш действителен. Значение по умолчанию -- 3 секунды (3000 миллисекунд).

[[concept_gss_n1l_hp__section_m11_3cl_y3b]]
=== Оптимизация ad hoc запросов

[NOTE]
====
[.note__title]#Важное замечание:# Оптимизация ad hoc запросов должна выполняться только по рекомендации специалиста технической поддержки {dv}.
====

Все запросы к Microsoft SQL Server можно разбить на две группы: вызов хранимых процедур, и выполнение т.н. "ad hoc"-запросов. В {dv} к первой группе относятся работа с представлениями и сохраненными поисковыми запросами, а ко второй группе -- различные выборки из карточек (серверный поиск строк секций).

В Microsoft SQL Server существует конфигурация "optimize for ad hoc workloads", оптимальная для работы с "ad hoc"-запросами. При использовании данной конфигурации будет оптимизирована работа с памятью и планами выполнения.

[NOTE]
====
[.note__title]#Прим.:# Описание параметра приведено в статье http://msdn.microsoft.com/ru-ru/library/cc645587.aspx; детальный разбор применения в статье http://blog.sqlauthority.com/2009/03/21/sql-server-2008-optimize-for-ad-hoc-workloads-advance-performance-optimization/.
====

Включается настройка через _advanced options_ следующим образом:

[source]
----
sp_CONFIGURE 'show advanced options',1
RECONFIGURE
GO
    
sp_CONFIGURE ‘optimize for ad hoc workloads’,1
RECONFIGURE
GO
----
