= Счетчики из категории Storage Server Methods

Счетчики из категории *Storage Server Methods* позволяют оценить соотношение времени, затраченного сервером на выполнение тех или иных операций.

Все операции разделены на следующие группы:

* "% Search" — все, что относится к поиску;
* "% Data Processing" — операции со строками карточек;
* "% Card Processing" — операции с самими карточками (создание, удаление);
* "% Cursor Processing" — операции с секциями карточек;
* "% File Processing" — операции с файлами;
* "% Link Processing" — операции с ссылками;
* "% Lock Processing" — операции с блокировками;
* “% Log Processing" — операции с журналом;
* "% Numerator Processing" — операции с нумераторами;
* "% Folder Processing" — операции с папками;
* "% Crypto Processing" — операции с шифрованием и подписанием;
* "% Security Processing" — операции с безопасностью и правами;
* "% View Processing" — операции с представлениями;
* "% Transformation Processing" — операции с преобразованиями;
* "% Report Processing" — операции с расширенными отчетами.

Каждой из этих групп операций (за исключением поиска) соответствует 2 счетчика. Первый из них (его имя совпадает с именем группы) показывает суммарное время, затраченное сервером на выполнение всех операций этой группы, при этом учитывается только время, которое было затрачено на обработку данных и передачу их клиенту (то есть время чистых вычислений).

Второй счетчик носит то же имя, но с приставкой SQL. Он характеризует только то время, которое было затрачено при выполнении данной группы методов на взаимодействие с базой данных (чтение, изменение, удаление данных).

Таким образом, сложив показания обоих счетчиков, можно получить суммарную величину времени (в секундах), затраченную сервером на выполнение операций данного типа.

На основании показаний этих счетчиков можно оценить, например, какие операции дают наибольшую нагрузку на сервер, или посмотреть распределение нагрузки в зависимости от времени.
