= Действия после установки системы

[#accounts]
== Настройка учетных записей сервисов {dv}

Администратор должен самостоятельно настроить права учетных записей служб
xref:6.1@platform::requirements-server-account.adoc[сервера {dv}], сервиса xref:6.1@platform::requirements-full-text-account.adoc[полнотекстового поиска] и xref:6.1@platform::requirements-file-service-account.adoc[файлового сервиса].

Рекомендуется назначить персональную лицензию учетной записи указанных сервисов. См. подробнее в документации модуля _{pl}_. раздел "xref:6.1@platform:console:manage-licenses.adoc#personalLicense[Назначение персональной лицензии]".

[#group]
== Настройка группы пользователей на контроллере домена

Если серверная часть модуля была установлена на компьютер, являющийся контроллером домена, нужно вручную добавить в локальную группу безопасности _{dv} Users_ пользователей, которые будут работать с системой {dv}.

[#console]
== Установка Консоли управления {dv}

Чтобы настроить модуль _Служба {ws}_, установите модуль _{mc}_ по инструкции в разделе установки модуля: "xref:6.1@mgmtconsole:admin:install.adoc[]".

{mc} позволяет настроить обязательный модуль _Служба {ws}_. Без данной настройки:

* Не будут создаваться и отправляться группы заданий.
* Не будут отправляться почтовые уведомления исполнителям.

[#commands]
== Полезные команды

Ниже перечислены команды, которые могут быть полезны при установке и после неё. Команды приведены на примере модуля {pl}. Чтобы применить команду для другого модуля, замените `platform` на название модуля.

. Посмотреть состояние сервиса:
+
[source,bash]
----
sudo systemctl status dvappserver
----
+
. Запустить сервис:
+
[source,bash]
----
sudo systemctl start dvappserver
----
+
. Остановить сервис:
+
[source,bash]
----
sudo systemctl stop dvappserver
----
+
. Перезапустить сервис:
+
[source,bash]
----
sudo systemctl restart dvappserver
----
+
// tag::log[]
. Посмотреть журнал сервиса (только записи в `stdout/stderr`):
+
[source,bash]
----
sudo journalctl -u dvappserver
----
+
. Посмотреть только самые последние записи в журнале и выводить новые записи по мере их появления:
+
[source,bash]
----
sudo journalctl -f -u dvappserver
----

// end::log[]

[start=7]
. Установить пакет:
+
[source,bash]
----
sudo apt-get install docsvision-platform
----
+
. Установить пакет определенной версии:
+
[source,bash]
----
sudo apt-get install docsvision-platform=6.0.1
----
+
. Удалить пакет:
+
[source,bash]
----
sudo apt-get purge docsvision-platform
----
