= Действия после установки системы

[#accounts]
== Настройка учетных записей сервисов {dv}

Администратор должен самостоятельно настроить права учетных записей служб
ifndef::install[]
xref:ROOT:requirements-server-account.adoc[сервера {dv}], сервиса xref:ROOT:requirements-full-text-account.adoc[полнотекстового поиска] и xref:ROOT:requirements-file-service-account.adoc[файлового сервиса].
endif::[]
ifdef::install[]
xref:requirements-server-account.adoc[сервера {dv}], сервиса xref:requirements-full-text-account.adoc[полнотекстового поиска] и xref:requirements-file-service-account.adoc[файлового сервиса].
endif::[]

Рекомендуется xref:console:manage-licenses.adoc#personalLicense[назначить персональную лицензию] учетной записи указанных сервисов.

[#group]
== Настройка группы пользователей на контроллере домена

Если серверная часть модуля была установлена на компьютер, являющийся контроллером домена, нужно вручную добавить в локальную группу безопасности _{dv} Users_ пользователей, которые будут работать с системой {dv}.

[#console]
== Установка Консоли управления {dv}

Чтобы настроить модуль _Служба {ws}_, установите модуль _{mc}_ по инструкции в разделе установки модуля: "xref:6.1@mgmtconsole:admin:install.adoc[]".

{mc} позволяет настроить обязательный модуль _Служба {ws}_. Без данной настройки:

* Не будут создаваться и отправляться группы заданий.
* Не будут отправляться почтовые уведомления исполнителям.

[#commands]
== Полезные команды

Ниже перечислены команды, которые могут быть полезны при установке и после неё. Команды приведены на примере модуля {pl}. Чтобы применить команду для другого модуля, замените `platform` на название модуля.

. Посмотреть состояние сервиса:
+
 $ sudo systemctl status platform
+
. Запустить сервис:
+
 $ sudo systemctl start platform
+
. Остановить сервис:
+
 $ sudo systemctl stop platform
+
. Перезапустить сервис:
+
 $ sudo systemctl restart platform
+
// tag::log[]
. Посмотреть журнал сервиса (только записи в `stdout/stderr`):
+
 $ sudo journalctl -u platform
+
. Посмотреть только самые последние записи в журнале и выводить новые записи по мере их появления:
+
 $ sudo journalctl -f -u platform

// end::log[]

[start=7]
. Установить пакет:
+
 $ sudo apt-get install platform
+
. Установить пакет определенной версии:
+
 $ sudo apt-get install platform=6.0.1
+
. Удалить пакет:
+
 $ sudo apt-get purge platform
