// Ранее было так:
// :asp: ASP.NET 4.6
// :platform:
// :installguide:
//
// include::partial$preconfigure-server.adoc[]
// partial до сих пор существует

= Предварительная настройка сервера Linux

// tag::preconfig[]
// . Подключите официальный репозиторий {dv} в качестве источника пакетов. Для этого необходимо отредактировать `/etc/apt/sources.list` при помощи текстового редактора, например, _nano_:
// +
// [source,bash]
// ----
// sudo nano /etc/apt/sources.list
// ----
// +
. В Astra Linux установите ПО, необходимое для подключения репозитория {dv} следующими командами:
+
[source]
----
sudo apt-get update
sudo apt-get install ca-certificates curl gnupg lsb-release
----
+
В РЕД ОС создайте файл для указания адреса репозитория:
+
[source]
----
sudo nano /etc/yum.repos.d/docsvision.repo
----
+
. Подключите официальный репозиторий {dv} в качестве источника:
+
[tabs]
====
Astra Linux::
+
[source,bash]
----
sudo curl -fsSLo /etc/apt/trusted.gpg.d/docsvision.asc https://packages.docsvision.com/linux/docsvision.asc
echo "deb https://packages.docsvision.com/linux/6.1/$(. /etc/os-release && echo $ID $VERSION_CODENAME) main" | sudo tee /etc/apt/sources.list.d/docsvision.list > /dev/null
sudo apt-get update
----

РЕД ОС::
+
[source,bash]
----
[docsvision]
name=Docsvision for RED OS $releasever
baseurl=https://packages.docsvision.com/linux/6.1/redos/8.0/$basearch/main
enabled=1
gpgcheck=1
gpgkey=https://packages.docsvision.com/linux/6.1/redos/docsvision.asc
----
====
+
. Подключите репозитории дополнительного ПО предпочтительным способом. Для РЕД ОС перейдите сразу к <<kerb,пункту 4>>.
+
* Используйте расширенный репозиторий Astra Linux:
+
[lowerroman]
.. В файле `/etc/apt/sources.list` раскомментируйте строку:
+
[source]
----
deb https://download.astralinux.ru/astra/stable/1.7_x86-64/repository-extended/ 1.7_x86-64 main contrib non-free
----
+
* Используйте репозиторий {ms}:
+
[lowerroman]
.. Подключите репозиторий следующими командами:
+
[source,bash]
----
sudo apt-get install packages-microsoft-prod
sudo apt-get update
----
+
.. Поднимите приоритет пакетов из репозитория {ms}, для этого создайте файл `/etc/apt/preferences.d/microsoft.pref` и добавьте в него следующие строки:
+
[source]
----
Package: dotnet* aspnet* netstandard*
Pin: origin packages.microsoft.com
Pin-Priority: 910
----
+
. [[kerb]]Чтобы иметь возможность использования сквозной аутентификации в {wc}е, {wincl}е, РМА и {of-mc} в Linux необходимо выполнить специальные настройки Kerberos и используемого браузера.
// end::preconfig[]
