// Ранее было так:
// :asp: ASP.NET 4.6
// :platform:
// :installguide:
//
// include::partial$preconfigure-server.adoc[]
// partial до сих пор существует

= Предварительная настройка сервера Linux

****
Инструкция по установке приведена для дистрибутива Astra Linux.
// , при установке {dv} на других xref:ROOT:requirements-software.adoc[поддерживаемых] дистрибутивах, в командах замените `astra` на имя дистрибутива Linux.
****

// tag::preconfig[]
// . Подключите официальный репозиторий {dv} в качестве источника пакетов. Для этого необходимо отредактировать `/etc/apt/sources.list` при помощи текстового редактора, например, _nano_:
// +
// [source,bash]
// ----
// sudo nano /etc/apt/sources.list
// ----
// +
. Установите ПО, необходимое для подключения репозитория {dv} следующими командами:
+
[source,bash]
----
sudo apt-get update
sudo apt-get install ca-certificates curl gnupg lsb-release
----
+
. Подключите официальный репозиторий {dv} в качестве источника:
+
----
curl -fsSL https://packages.docsvision.com/astra/gpg | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/docsvision.gpg
echo "deb https://packages.docsvision.com/astra $(lsb_release -cs) 6.1" | sudo tee /etc/apt/sources.list.d/docsvision.list > /dev/null
sudo apt-get update
----
+
Репозитории доступны для Astra Linux.
// , Ubuntu или Debian. Для установки на Ubuntu и Debian необходимо в адресе заменить `/astra` на `/ubuntu` или `/debian` соответственно.
+
. Подключите репозитории дополнительного ПО предпочтительным способом:
+
* Используйте расширенный репозиторий Astra Linux:
+
[lowerroman]
.. В файле `/etc/apt/sources.list` раскомментируйте строку:
+
[source]
----
deb https://download.astralinux.ru/astra/stable/1.7_x86-64/repository-extended/ 1.7_x86-64 main contrib non-free
----
+
* Используйте репозиторий {ms}:
+
[lowerroman]
.. Подключите репозиторий следующими командами:
+
[source,bash]
----
sudo apt-get install packages-microsoft-prod
sudo apt-get update
----
+
.. Поднимите приоритет пакетов из репозитория {ms}, добавив в файл `/etc/apt/preferences.d/microsoft.pref` следующие строки:
+
[source]
----
Package: dotnet* aspnet* netstandard*
Pin: origin packages.microsoft.com
Pin-Priority: 910
----
+
.. Подключите репозиторий следующими командами:
+
[source,bash]
----
sudo apt-get install packages-microsoft-prod
sudo apt-get update
----
+
. Чтобы иметь возможность использования сквозной аутентификации в {wc}е, {wincl}е, РМА и {of-mc} в Linux необходимо выполнить специальные настройки Kerberos и используемого браузера.
// end::preconfig[]
