= Настройка полнотекстового поиска

Полнотекстовый поиск в системе {dv} – это поиск карточек, содержащих заданную строку в данных и/или в связанных файлах.

Во время полнотекстового поиска может выполняться:

* поиск точного совпадения слов;
* поиск слов, начинающихся с заданной последовательности букв, например, по ключевому слову "приказ" будут отобраны слова "приказываю", "приказать" и т. д.;
* морфологический поиск – поиск с учетом словоформ.

Полнотекстовый поиск возможен по данным, которые были проиндексированы сервисом полнотекстового индексирования {dv}. Данный сервис передает данные, по которым должна быть поддержана возможность поиска, во внешнюю систему поиска, которая непосредственно индексирует данные и предоставляет ответы на поисковые запросы.

{dv} поддерживает две системы полнотекстового поиска:

* встроенная в Microsoft SQL Server система поиска – только для БД Microsoft SQL Server;
* система полнотекстового поиска "Elasticsearch" – для БД Microsoft SQL Server и PostgreSQL.

База данных может быть настроена на работу только с одной системой полнотекстового поиска. К сервису полнотекстового индексирования могут быть подключены несколько баз данных {dv}, индексируемых с помощью разных систем полнотекстового поиска.

*Обратите внимание*:

. После добавления новых данных (например, создания карточки) должно пройти определенное время, прежде чем эти данные станут доступны для нахождения поиском в клиентской программе. Временной промежуток между добавлением данных и формированием индексов определяется периодом формирования очереди обработки (выполняется задачей в SQL Server; периодичность выполнения – 5 минут) и периодом обработки этой очереди сервисом полнотекстового индексирования.
. Из особенностей формирования индексов с учетом морфологии языка, качество поиска в Elasticsearch и в SQL Server может различаться:
* Для поиска в SQL Server может передаваться более короткая часть искомого слова, чем необходима Elasticsearch. Например, для поиска документов с названием "Исходящий …" с помощью SQL Server пользователю достаточно ввести "исх", в Elasticsearch – "исходящ".
* Результаты поиска в Elasticsearch могут содержать записи, не полностью совпадающие со словами поисковой фразы (менее жесткий поиск, чем в SQL Server). Например, при поиске по фразе "исходящ ном2", результат может содержать записи "Исходящий номер1", "Исходящий номер2" и т.п.
* В некоторых вариантах поисковой фразы Elasticsearch может не возвращать результаты.
. Полнотекстовый поиск по содержимому файлов карточек поддерживается только для файлов:
* при использовании встроенной в Microsoft SQL Server система поискаxref:#fntarg_1[^1^]: PDF и файлы Microsoft Office;
* при использовании системы полнотекстового поиска "Elasticsearch"xref:#fntarg_2[^2^]: PDF, файлы Microsoft Office (DOCX, DOC, XLSX, XLS, PPTX, PPT, RTF), HTML и TXT.
. При настройке любой системы полнотекстового поиска, выбирайте для индексации не поля _Регистрационный номер_, _Исходящий номер_ в секции _Основная информация_, а секцию _Номера_, когда необходимо проиндексировать номер документа.
+
В прочих карточках необходимо следовать схожей логике: проверять наличие похожей секции и при необходимости выбирать её.

* *xref:../topics/ConfigureFulltextSQLServer.adoc[Подключение полнотекстового поиска Microsoft SQL Server]* +
* xref:ConfigureFulltextElastic.adoc[Подключение полнотекстового поиска Elasticsearch]* +
* xref:FullText_Search_Service_Edit_Settings.adoc[Изменение настроек полнотекстового поиска]* +
* xref:DetachDbFromFulltextService.adoc[Отключение полнотекстового индексирования]* +
* xref:InstallFulltextNode.adoc[Отдельная установка сервиса полнотекстового индексирования]* +
* xref:FulltextInCluster.adoc[Особенности настройки кластера сервисов полнотекстового индексирования]* +
* xref:FulltextLogConfiguration.adoc[Протоколирование работы сервиса полнотекстового индексирования]* +


xref:#fnsrc_1[^1^] Должен быть установлены компоненты Microsoft Office 2010 Filter Packs и Adobe PDF IFilter 11.0.1.

xref:#fnsrc_2[^2^] Должно быть установлено расширение "Ingest Attachment Processor" для Elasticsearch
