[[ariaid-title1]]
== Настройка распределенного серверного кэша

Важным условием для корректной работы системы Docsvision, включающей несколько процессов сервера Docsvision (работает веб-сервис Docsvision в IIS и служба StorageServer, или в настройках пула приложений IIS, в котором работает сервис Docsvision, параметр «Maximum Worker Processes» установлен в значение 2 и более, или работает кластер серверов Docsvision), является использование всеми процессами общего серверного кэша – рассинхронизация кэша может стать причиной появления неактуальных данных и других ошибок. В качестве хранилища распределенного кэша в Docsvision выступает кэш-сервер Redis.

[NOTE]
====
[.note__title]#Важное замечание:# Для работы с Redis лицензия Docsvision должна содержать опцию «Docsvision кеш-сервер Redis». Отсутствие лицензии приведёт к ошибке в работе сервера Docsvision.
====

Redis может быть установлен на компьютер с сервером Docsvision или на отдельный компьютер. Совместимая версия Redis: *3.2.100*.

[NOTE]
====
[.note__title]#Прим.:# Инструкцию по установке Redis см. в документации к кэш-серверу (https://redis.io/). Также установка и настройка Redis рассмотрена в статье https://docsvision.zendesk.com/hc/ru/articles/360001473836-Redis-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%B8-%D0%BA%D0%B0%D0%BA-[Redis. Зачем и как?] на сайте Docsvision. Системные требования Redis можно установить исходя из желаемой производительности, основываясь на данных в статье https://redis.io/topics/benchmarks[How fast is Redis?], и требованиях Redislabs (см. https://docs.redislabs.com/latest/rs/administering/designing-production/hardware-requirements/).
====

=== Требования к настройке Redis

После установки Redis измените настройки в конфигурационном файле Redis ([.ph .filepath]`redis.conf`):

. Отключите сохранение резервных копий данных на диск.
[loweralpha]
.. Закомментируйте строки:
+
[source,pre,codeblock]
----
save 900 1
save 300 10
save 60 10000
----
.. Установите значение параметра `appendonly` в «no» (по умолчанию).
. Измените политику перезаписи данных при нехватке памяти на «allkeys-lru» (удаление наименее используемых данных):
+
[source,pre,codeblock]
----
maxmemory-policy allkeys-lru
----
. Перезапустите Redis.

=== Подключение Redis к Docsvision

. Откройте Консоль настройки Docsvision
. Перейдите в раздел настроек [.ph .menucascade]#[.ph .uicontrol]*Настройки сервера* > [.ph .uicontrol]*Базы данных*#.
. Выберите настраиваемую базу данных, при работе с которой сервер будет кэшировать данные в Redis, и нажмите на кнопку [.ph .uicontrol]*Настройки*. Будет открыто окно [.keyword .wintitle]*Свойства и управление базой данных*.
. Перейдите на вкладку xref:ControlPanelCaching.adoc[Настройки кэширования].
. Выберите в списке [.ph .uicontrol]*Провайдер* значение «Redis». Будет разблокировано поле [.ph .uicontrol]*Строка подключения*.
. Введите в поле [.ph .uicontrol]*Строка подключения* адрес и порт для подключения к компьютеру с Redis в формате «[IP адрес]:[Порт]». По умолчанию Redis использует порт 6379.
+
Сетевые политики должны разрешать подключения с серверов Docsvision к Redis.
. Нажмите на кнопку [.ph .uicontrol]*Тест*, чтобы проверить соединение с Redis. Результат проверки («Успешно», «Ошибка») отобразится в диалоговом окне.
. Сохраните изменения настроек базы данных.
. Если настраивается кластер серверов Docsvision, подключите все сервера к одному кеш-сервер Redis.

*На уровень выше:* xref:../topics/Administrator_functions.adoc[Функции администратора]
