= Настройки агрегации

Перед настройкой убедитесь, что конфигурация {es} соответствует xref:ROOT:requirements-hardware.adoc#elastic[указанным] требованиям.

Для работы агрегации в {wc}е необходимо xref:search-elastic.adoc[установить] полнотекстовый поиск {es} и создать файл конфигурации.

Файл конфигурации может дополняться администратором. В файл конфигурации агрегатов могут быть включены настройки для разных типов карточек, в том числе для пользовательских типов. Чтобы настроить разные агрегаты в зависимости от типа карточки, укажите тип, секцию и поле карточки. Можно также указать вложенные секции.

Один из агрегатов может обозначен как главный, который в дальнейшем будет выделяться в представлении {wc}а. Для каждого агрегата можно задать локализуемое имя.

== Создание файла настроек

.Чтобы сделать функцию агрегации доступной:
. xref:search-elastic.adoc[Установите] полнотекстовый поиск {es}.
. Создайте файл конфигурации.
+
CAUTION: Файл конфигурации должен быть создан до настройки полнотекстового поиска через серверную консоль.
+
Файл конфигурации содержит первичные настройки данных в формате JSON.
+
.Пример файла конфигурации:
[source,json]
----
{
	"AggreagationItems": [
        {
		"SectionId": "00000000-0000-0000-0000-000000000000", <.>
		"FieldId": "00000000-0000-0000-0000-000000000000", <.>
		"IsMain": true, <.>
		"LocaleNames": { <.>
			"1049": "Тип карточки",
			"1033": "CardTypeAgg"
		},
		"IsGroup": false, <.>
		"Alias": "CardTypeAgg" <.>
	},


	{
		"SectionId": "30EB9B87-822B-4753-9A50-A1825DCA1B74",
		"FieldId": "8C2F3AEF-D178-4245-B6DF-C809C7642779",
		"IsMain": false,
		"LocaleNames": {
			"1049": "Имя",
			"1033": "Name"
		},
		"IsGroup": true,
		"Alias": "NameAgg"
	},
	{
		"SectionId": "20D21193-9F7F-4B62-8D69-272E78E1D6A8",
		"FieldId": "F5C843C0-5CE1-4727-81BF-0C764A43243B",
		"IsMain": false,
		"LocaleNames": {
			"1049": "Имя",
			"1033": "Name"
		},
		"IsGroup": true,
		"Alias": "NameAgg"
	},


	{
		"SectionId": "30EB9B87-822B-4753-9A50-A1825DCA1B74",
		"FieldId": "fe57ac59-a298-4f9b-9c85-e85d771041e8",
		"LinkedFieldsAliases": [ "DisplayString" ], <.>
		"IsMain": true,
		"IsGroup": true,
		"Alias": "AuthorAggWithLinks"
	},
	{
		"SectionId": "20D21193-9F7F-4B62-8D69-272E78E1D6A8",
		"FieldId": "40411b9e-2ed8-4edb-975a-1f66e6da93e5",
		"LinkedFieldsAliases": [ "FirstName", "LastName", "AccountName" ],
		"IsMain": true,
		"IsGroup": true,
		"Alias": "AuthorAggWithLinks"
	}
    ]
}
----
<.> `SectionId` -- идентификатор секции. Если `SectionId` = `Guid.Empty`, то это агрегат по `CardTypeId`.
<.> `FieldId` -- идентификатор поля.
<.> `IsMain` -- метка главного агрегата.
<.> `LocaleNames` -- локализованное имя агрегата для каждого языка БД.
<.> `IsGroup` -- метка о том, что агрегат необходимо собирать из нескольких полей.
<.> `Alias` -- условное имя для агрегата. Агрегаты с флагом `IsGroup` будут группироваться по данному имени.
<.> `LinkedFieldsAliases` -- если поле является ссылкой на справочник, необходимо использовать дополнительное поле. В поле задаётся список полей из словаря, которые будут использоваться для агрегации. Эти поля должны быть доступны и включены в настройках полнотекстового поиска, в противном случае они будут проигнорированы.
+
Все поля сверяются с метаданными и включенными настройками полнотекстового поиска. Если поля не соответствуют настройкам системы, они будут проигнорированы.
+
. Первичные настройки будут преобразованы в конечные при использовании метаданных БД и настроек индексов:
+
* Проверяется наличие секций и полей в метаданных, будут получены их имена.
* Проверяется наличие карточек, секций, полей в настройках индексирования.
* Если поля ссылочные, проверяется, настроено ли индексирование соответствующих справочников, преобразуются имена дополнительных полей.
+
. Сохраните файл, например, под именем `AggSettings.conf`.
+
Путь к файлу настроек будет получен из реестра, из параметра `FullTextIndexing_AggregationSettingsFilePath` по пути `HKEY_LOCAL_MACHINE\SOFTWARE\DocsVision\Platform\5.5\Server`.
+
В параметре указываются пути по аналогии с узлом Database: ключ - alias базы в нижнем регистре, значение -- путь к файлу настроек.
+
. После завершения настройки, перезапустите IIS.
