= Группы безопасности {dv}

В процессе установки и настройки серверной части модуля будут созданы группы безопасности пользователей. 

TIP: Если группы уже существуют на момент установки, их состав не изменяется.

== Основные группы безопасности

DocsVision Users::
Члены группы имеют права на работу с системой {dv}.
+
По умолчанию в группу включаются все пользователи, входящие в группу безопасности _Все_ (_Everyone_). Пользователи этой группы по умолчанию имеют уровень допуска `самый низкий`; при необходимости их уровень допуска может быть переопределен в _Справочнике сотрудников_.

DocsVision Power Users::
Члены группы имеют права просмотра всех объектов системы {dv}, включая чтение системного журнала, исключая, возможность изменения прав доступа.
+
По умолчанию пользователи в эту группу не включаются.

{dv-admins-serv}::
Члены группы -- администраторы {dv}, имеют право доступа к БД, ряду административных функций, а также возможность чтения и предоставления прав доступа (но не изменения назначенного уровня безопасности) ко всем объектам базы данных.
+
Пользователь, входящий в эту группу может архивировать и разархивировать карточки, на которые у него есть права, находить в архиве любые карточки, отображать содержимое архива в представлении {wincl} и РМА;
+
Пользователи этой группы всегда имеют уровень допуска `высокий`, несмотря на то, какой уровень указан для конкретного пользователя в Справочнике сотрудников.
+
В группу автоматически включается пользователь, настроивший систему {dv}.

{dv-sec-admins-serv}::
Члены группы обладают всеми правами *{dv-admins-serv}*, а кроме того могут изменять уровни безопасности, назначенные субъектам и объектам системы.
+
Пользователи, входящие в эту группу могут архивировать, разархивировать и находить в архиве любые карточки.
+
Пользователи этой группы всегда имеют уровень допуска `самый высокий`, несмотря на то, какой уровень указан для конкретного пользователя в Справочнике сотрудников.
+
В группу автоматически включается пользователь, настроивший систему {dv}.

DocsVision Archive Operators::
Члены группы имеют право архивировать и разархивировать и находить в архиве только те карточки {dv}, на работу с которыми у них есть права (минимальные требования -- права на чтение и изменение).
+
Группа создаётся на сервере {dv} и используется для проверки прав при работе с архивом. По умолчанию пользователи в эту группу не включаются.
+
Участникам группы предоставляются права группы _DocsVision Users_.

== Дополнительные группы безопасности

DocsVision Workflow Process Creators::
Члены группы имеют право создавать и редактировать шаблоны и экземпляры БП модуля _{wf}_. Поскольку БП во время исполнения имеет доступ к защищенным объектам, состав этой группы не менее важен, чем состав группы *{dv-admins-serv}*.
+
Участникам группы предоставляются права группы _DocsVision Users_.
+
В группу автоматически включается пользователь, настроивший систему {dv}.

DocsVision Search Query Creators::
Члены группы имеют право работать с окном расширенного поиска (вызывать окно поиска из приложения {wincl}, создавать и сохранять поисковые запросы), создавать и редактировать личные и общие запросы, удалять и импортировать общие запросы _Личного помощника_.
+
По умолчанию в эту группу включаются все пользователи, входящие в группу безопасности _Все_ (_Everyone_).
+
Пользователям, включённым в группу _{dv} Search Query Creators_, должны быть предоставлены права на чтение и изменение системной папки `Результаты поиска`.
+
Участникам группы предоставляются права группы _DocsVision Users_.
