[[ariaid-title1]]
== Назначение прав доступа на папки

Чтобы назначить дискреционные права доступа на папки:

. [.ph .cmd]#Откройте Консоль настройки Docsvision и перейдите в раздел [.keyword .wintitle]*Права папок*.#
. [.ph .cmd]#Выберите папки, на которые назначаются права доступа, в левой панели.#
. [.ph .cmd]#Настройте права доступа:#
[loweralpha]
.. [.ph .cmd]#Нажмите на кнопку [.ph .uicontrol]*…* справа от списка [.ph .uicontrol]*Конфигурация прав на папки*. Будет открыто стандартное диалоговое окно настройки прав доступа Windows.#
.. [.ph .cmd]#Предоставьте требуемые права пользователям или группам.#
. [.ph .cmd]#Если требуется, установите флаг [.ph .uicontrol]*Добавлять права к существующим*.#
. [.ph .cmd]#Если требуется, установите флаг [.ph .uicontrol]*Обрабатывать подпапки*.#
. [.ph .cmd]#Нажмите на кнопку *Назначить права*. Настроенные права будут применены.#

Права на отдельные папки также могут быть выданы при помощи настроек дискреционной безопасности в Windows-клиенте или РМА (см. документ [.ph]#[.dfn .term]_Модуль «Docsvision 5. Windows-клиент». Руководство пользователя_#, пункт «Управление доступом к объектам»).

*Parent topic:* xref:../topics/Administrator_functions.adoc[Функции администратора]
