= Настройка внешних хранилищ

== Общие сведения

Файлы в системе {dv} имеют две составляющие: атрибутивную и бинарную.

Атрибутивная часть файла::
Часть файла, содержащая его атрибуты: название, дату создания, изменения, размер. Атрибутивная часть хранится в БД {dv}.

Бинарная часть файла::
Часть файла, с его содержимым. Бинарная часть может также храниться в БД или во внешнем хранилище следующих типов:
+
- Файловая система.
- Внешняя БД или FileStream внешней БД.
- Внешние хранилища других типов. Если для работы с этими хранилищами были реализованы программные компоненты, например, провайдеры к внешним хранилищам.

К серверу {dv} могут быть одновременно подключены несколько хранилищ разных типов. Администратор должен настроить правила, по которым бинарные данные будут распределяться между подключенными хранилищами.

.Администратору доступны следующие инструменты настройки правил:
. Разделы хранилища -- метки, назначаемые внешним хранилищам. Метки определяют возможность сохранять бинарные данные файлов в зависимости их оперативного состояния.
+
.В {dv} есть следующие типы разделов внешних хранилищ:
* _Основные_ -- раздел предназначен для сохранения бинарных данных файлов, не являющихся архивными или временными.
* _Архивные_ -- раздел предназначен для сохранения бинарных данных файлов карточек, помещённых в архив.
* _Временные_ -- раздел предназначен для временного хранения бинарных данных файлов, которые ещё не загружены, но находятся в процессе загрузки в {dv}.
+
. Группа хранилищ -- сущность, объединяющая несколько хранилищ одного или разных типов. Для каждой группы устанавливается своё правило распределения бинарных данных файлов между хранилищами группы.
. Правила помещения в хранилища -- определяет целевую группу хранилищ для бинарных данных файлов. Целевая группа определяется в зависимости от параметров сохраняемого файла.
. Группа хранилищ по умолчанию -- определяет целевую группу хранилищ по умолчанию для файлов с определённым оперативным состоянием (основные, архивные, временные). Данная группа хранилищ будет выбрана для файлов, для которых сервер {dv} не смог определить подходящее правило помещения в хранилища.

== Алгоритм выбора внешнего хранилища для бинарных данных файла

. Проверяется выполнение условий правил помещения в хранилище:
* Если условия выполнены, выбирается группа хранилищ, соответствующая правилу.
* Если условия не выполнены, выбирается группа хранилищ по умолчанию для файлов с данным оперативным состоянием (основные, архивные, временные).
. Из выбранной группы хранилищ выбирается хранилище для сохранения данных файла:
.. Определяются хранилища, в которые может быть добавлен файл с его типом. Например, если файл является временным, будут выбраны только хранилища, допускающие сохранение временных файлов.
.. Выбирается целевое хранилище для данных файлов. Хранилище выбирается исходя из режима выбора, установленного для группы хранилищ.
+
WARNING: Данные файла размещаются в хранилище во время загрузки файла в БД и не перемещается между хранилищами при создании или изменении хранилищ.

== Стандартная последовательность подключения внешнего хранилища

.Чтобы подключить внешнее хранилище к серверу {dv}, администратору потребуется:
. Настроить параметры подключения к внешнему хранилищу:
+
* Указать данные для подключения к внешней БД.
* Указать путь для сохранения файлов и т.п.
+
. Создать для хранилища новую группу или включить его в существующую.
. Для новой группы хранилищ настроить правила помещения данных в это хранилище.

== Важные условия настройки внешних хранилищ

* Для основных, архивных и временных файлов должна быть выбрана группа хранилищ по умолчанию. Это может быть одна группа хранилищ или разные группы (для каждого типа своя группа). Хранилища из данных групп используются по умолчанию, если для файла не найдено более подходящее хранилище.
** В каждой группе хранилищ по умолчанию должно быть как минимум одно хранилище, имеющее как минимум один раздел для файлов соответствующего оперативного состояния.
* Для вытесняемых в офлайн файлов должна быть назначена группа хранилищ по умолчанию.
** Правила помещения в хранилища должны иметь более высокий приоритет по сравнению с группой хранилищ по умолчанию. Иными словами, если добавляемый файл удовлетворяет определённому правилу, будет выбрано хранилище из данного правила. Если же файл не удовлетворяет ни одному правилу, будет выбрана группа хранилищ по умолчанию.
+
include::partial$excerpts.adoc[tags=storageLimits]
