[[ariaid-title1]]
== Важные условия настройки внешних хранилищ

* Для основных, архивных и временных файлов должна быть выбрана группа хранилищ по умолчанию. Это может быть одна группа хранилищ или разные группы (для каждого типа своя группа). Хранилища из данных групп используются, когда не найдены другие хранилища, подходящие для сохранения файла.
* Группа хранилищ по умолчанию для основных, архивных или временных файлов должна содержать минимум одно хранилище с разделом, позволяющим сохранять файлы с соответствующим оперативным состоянием.
* Должна быть назначена группа хранилищ по умолчанию для вытесняемых в офлайн файлов.
* Приоритет правила помещения в хранилище выше чем приоритет использования группы хранилищ по умолчанию, т. е. если добавляемый файл удовлетворяет определенному правилу, то будет выбрано хранилище из данного правила, а если файл не удовлетворяет ни одному правилу – будет выбрана группа хранилищ по умолчанию.
* Для СУБД Microsoft SQL Server существует ограничение на размер добавляемых файлов: не более 2 ГБ. Если в Docsvision необходимо хранить файлы больше 2 ГБ используйте для них внешнее хранилище, поддерживающее файлы такого размера (например, «Хранилище на диске» или Filestream). Для СУБД PostgreSQL аналогичное ограничение составляет 1 ГБ.

*Parent topic:* xref:../topics/External_Data_Storage.adoc[Настройка внешних хранилищ Docsvision]
