[[ariaid-title1]]
== Изменение времени ожидания выполнения команды SQL

В процессе настройки сервера Docsvision операция, связанная с изменением данных в БД, может завершиться с ошибкой из-за превышения времени ожидания её выполнения.

Для устранения ошибки можно увеличить время ожидания. Значение времени ожидания устанавливается непосредственно перед выполнением операции – верно для операций создания, обновления и добавления БД.

Для операций обновления БД в консольном режиме (используется, например, при автоматическом обновлении при установке новых версий модулей), преобразования динамических метаданных в расширенные и при сохранении настроек журналирования (xref:ControlPanelLog.adoc[Страница настроек «Журнал»]) значение времени ожидания получается из реестра ОС сервера Docsvision: ветка [.ph .filepath]`HKLM\SOFTWARE\DocsVision\Platform\5.5\Server`, параметр `SqlCommandTimeout`. Значение в секундах.

*Parent topic:* xref:../topics/Administrator_functions.adoc[Функции администратора]
