= Обновление программных компонентов собственных решений

В новой версии изменился механизм проверки соответствия клиентских компонентов библиотек карточек.

.Если в Решении на базе {dv} реализованы собственные библиотеки карточек, необходимо:
. Подключить новые сборки {dv} к проекту компонента.
. Добавить в ресурсы XML-файл с описанием библиотеки карточек.
. В реализацию класса `CardLibrary` -- если .NET-сборка -- добавить переопределение метода `GetLibraryDefinition`. Метод должен возвращать описание библиотеки карточек.
+
[source,csharp]
----
   protected override string GetLibraryDefinition()
   {
     return Resources.CardLibDefinition;
   }
----
+
. Повторно собрать, протестировать работоспособность и распространить клиентский компонент библиотеки карточек.

.Для С++-реализации клиентского компонента библиотеки карточек необходимо:
. Поддержать интерфейс `ICardLibraryInfo2`.
. Изменить поведение свойства `ICardLibraryInfo.Version`.

См. реализацию в примере `netstatSolution`, в документации руководства разработчика "xref:6.1@programmer:samples:solution/snap-in/new-snap-in.adoc[]".