= Список изменений в версии

Пропустить обновление УД и КС::
При обновлении, создании или подключении существующей БД появилась возможность пропустить загрузку в БД версий модулей "{dm}" и "{ad}".

Управление кэшем ролевой модели::
Появилась возможность xref:admin:cache-invalidation.adoc[управлять временем жизни] в кеше операндов собственных хранимых процедур.

Различия в имени компьютера для COM и REST::
Формат имени машины в свойствах сессии для COM и REST object manager приведён к единообразию. Подключение с одной машины через COM и REST занимает только одну лицензию.

Работа с {es}::
Обновлена рекомендуемая версия полнотекстового поиска {es}. Теперь актуальная версия {es} 7.9. См. xref:admin:search-elastic.adoc[].

Настройки фасетов::
Добавлена возможность xref:admin:search-elastic-change.adoc#facets[настройки фасетов] {es}, чтобы иметь возможность работать с агрегацией в {wc}е.

Адрес {of-sett-serv}::
В разделе xref:admin:console-server.adoc["Сервер"] программы {cns} появилась возможность указать адрес _{of-sett-serv}_. Адрес определяется {wincl}ом и позволяет открыть страницу карточки в {of-mc}.

== Оптимизации

* Оптимизирована скорость выполнения процедур вида *dvsys_help_drop*: *dvsys_help_drop_views* и *dvsys_help_drop_search*.