= Изменения в релизной версии

Добавление расширений авторизации::
Появилась возможность xref:admin:authorization-extensions.adoc[добавить] сторонние расширения авторизации.

Пропустить обновление УД и КС::
При обновлении, создании или подключении существующей БД появилась возможность пропустить загрузку в БД версий модулей _{dm}_ и _{ad}_.
+
Не пропускайте загрузку в БД версий модуля _{ad}_, чтобы иметь возможность создать xref:approval:admin:route-create.adoc#improved[усовершенствованное согласование].

Управление кэшем ролевой модели::
Появилась возможность xref:admin:cache-invalidation.adoc[управлять временем жизни] в кэше операндов собственных хранимых процедур.

Различия в имени компьютера для COM и REST::
Формат имени машины в свойствах сессии для COM и REST object manager приведён к единообразию. Подключение с одной машины через COM и REST занимает только одну лицензию.

Работа с {es}::
Обновлена рекомендуемая версия полнотекстового поиска {es}. Теперь актуальная версия {es} 7.9. См. xref:admin:search-elastic.adoc[].

Настройки фасетов::
Добавлена возможность xref:admin:search-elastic-change.adoc#facets[настройки фасетов] {es}, чтобы иметь возможность работать с агрегацией в {wc}е.

Адрес {of-sett-serv}::
В разделе xref:admin:console-server.adoc["Сервер"] программы {cns} появилась возможность указать адрес _{of-sett-serv}_. Адрес определяется {wincl}ом и позволяет открыть страницу карточки в {of-mc}.

== Оптимизации

* Оптимизирована скорость выполнения процедур вида *dvsys_help_drop*: *dvsys_help_drop_views* и *dvsys_help_drop_search*.
* Оптимизирован расширенный отчёт `dvreport_get_data_\{3d695ba8-2815-4785-b251-9c551ddbd3db}` для поиска по индексу вместо полного просмотра.
* Оптимизировано ведение журналов системы.
+
Журналы работы сервера и Консоли настройки {dv} создаются автоматически и будут записаны в резервные папки, если папка по умолчанию недоступна. См. подробнее "xref:admin:logs.adoc[]".
+
Журналы полнотекстового поиска теперь архивируются каждый день. См. подробнее "xref:admin:search-logging.adoc[]".
