= Ограничения на изменение стандартных настроек

== Ограничения на изменение настроек видов карточекя

При работе с конструкторами и справочниками {dv} *запрещено* изменять настройки корневых видов карточек, добавляемых модулем _Базовые объекты_: _Документ_, _Задание_, _Группа заданий_, _Согласование_, _Этап согласования_, _Маршрут согласования_ и др.

TIP: Создайте дочерний вид и работайте с ним. Настройки собственных видов разрешено изменять без ограничений.

== Ограничения на изменение настроек папок

* Запрещено удалять или перемещать папку "Папки".

== Ограничения на изменение базы данных

Компания "ДоксВижн" разрешает (а в некоторых случаях -- рекомендует) партнерам и заказчикам прямое подключение к базе данных, с учетом нижеперечисленных ограничений и условий.

=== Запрещено

* Удаление (`DELETE`) или изменение (`ALTER`) структуры служебных таблиц базы данных, а также таблиц с данными,
include::partial$chunks.adoc[tags=utils]
+
* Удаление (`DELETE`) или изменение (`ALTER`) стандартных хранимых процедур, функций и триггеров,
include::partial$chunks.adoc[tags=utils]
+
* Удаление или изменение уникальных ограничений (`CONSTRAINTS`),
include::partial$chunks.adoc[tags=utils]
+
* Удаление или изменение данных (строк, значений полей) служебных таблиц базы данных (в частности, *dvsys_*, *dvtable_*); а также таблиц с данными,
include::partial$chunks.adoc[tags=utils]
+
* Удаление или изменение стандартных служебных задач (`JOBS`).

=== Разрешено

* Создание любых собственных временных или постоянных таблиц в базе данных, например с целью импорта/экспорта данных в другие системы.
* Создание собственных хранимых процедур в базе данных, необходимых для реализации прикладной бизнес-логики решения.
* Создание собственных хранимых процедур в базе данных, предназначенных для вычисления специфических ролей в ролевой модели.
* Создание собственных регулярных задач (`JOBS`).
* Добавление собственных кластерных и некластерных индексов, а также изменение стандартных индексов для таблиц с данными,
include::partial$chunks.adoc[tags=utils]
+
* Изменять разбивку и размещение файлов базы данных на физических дисках.
* Настройка и выполнение регулярных операций по администрированию базы данных `BACKUP`, `MAINTANANCE` и так далее.

=== Ограничено разрешено

Следующие действия разрешены, если их выполнение было согласовано с компанией "ДоксВижн":

* Вставка новых строк (`INSERT`) служебных таблиц базы данных; а также таблиц с данными,
include::partial$chunks.adoc[tags=utils]
Например, такой механизм может быть полезен в случае массового импорта данных из других систем.
+
* Добавление собственных триггеров для служебных таблиц базы данных, а также таблиц с данными,
include::partial$chunks.adoc[tags=utils]

=== Дополнительные условия и ограничения

В рамках гарантийной технической поддержки компания "ДоксВижн":

- Не оказывает консультаций.
- Не дает ответов на вопросы о структуре базы данных,  назначению отдельных таблиц, хранимых процедур, индексов и ограничений.
- Не дает консультаций по оптимизации индексов или размещению файлов базы данных.

TIP: Подобные вопросы могут быть решены через службу консалтинга при условии наличия действующего абонемента.
