// tag::twobasesonepath[]
[WARNING]
====
* При настройке собственных хранилищ с отличными от стандартных путями, существует возможность указать одинаковые пути для разных БД. Чтобы избежать нежелательного удаления всех основных или архивных файлов с закончившимся сроком хранения для сразу двух БД, не рекомендуется указывать одинаковые пути в настройках для хранилищ разных БД.
* Когда *{sss}* и *{fss}* запущены под разными учётными записями и используются пути по умолчанию, например, `%TEMP%` для временного хранилища, возможны случаи неудаления файлов с закончившимся сроком хранения. Причина в разных относительных путях для разных УЗ.
+
Чтобы избежать подобной ситуации, указывайте абсолютный путь к временному хранилищу и обеспечивайте необходимый доступ по этому пути для обоих учетных записей. Также можно запускать *{sss}* и *{fss}* под одной учетной записью.
====
// end::twobasesonepath[]

// tag::do-not-skip[]
[WARNING]
====
Пропускайте загрузку настроек модулей _{dm}_ и _{ad}_ в базу данных, только если уверены. Это может вызвать критические ошибки при выполнении операций, связанных с модулями, и сделать невозможным корректное обновление системы в будущем.
====
// end::do-not-skip[]